### ISSUE TITLE
Can't connect to projects (error=63, File name too long)

### ISSUE THREAD

**Issue by fabianpage** [LightTable/LightTable#1090]
Hi

I have problems to connect to clojure projects. Today i deleted my LightTable clone and made a fresh clone from github. Since then i can't connect to any project anymore.

Fabian

```
final project:  ([org.clojure/clojure "1.5.1"] [expectations/expectations "1.4.56"] [org.clojure/core.typed "0.2.21"] [org.clojure/tools.nrepl "0.2.3" :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete "0.2.3" :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl "0.0.10"] [org.clojure/tools.reader "0.7.10"])
java.io.IOException: Cannot run program "java" (in directory "/Users/fabian/tmp/ltKata/string-calculator"): error=63, File name too long
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
    at java.lang.Runtime.exec(Runtime.java:617)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at leiningen.core.eval$sh.doInvoke(eval.clj:159)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:617)
    at leiningen.core.eval$fn__2081.invoke(eval.clj:224)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.repl$repl.doInvoke(repl.clj:253)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at leiningen.light_nrepl.main(Unknown Source)
Caused by: java.io.IOException: error=63, File name too long
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
    ... 25 more
```

**Comment by cldwalker** [comment]
Going through old issues and found this. @henrik242 How did you see your "envBlock"? Did this just show up when using `ps`?

**Comment by henrik242** [comment]
@cldwalker Nah, I had to attach the process to a debugger and look at the parameter within `java.lang.UNIXProcess.forkAndExec()`
