### ISSUE TITLE
SyntaxError: Unexpected token . when using require in ClojureScript

### ISSUE THREAD

**Issue by joladev** [LightTable/LightTable#1164]
I am able to evaluate most ClojureScript, but as soon as I try to import anything (require, ns), I get this error:

```
SyntaxError: Unexpected token .
    at eval (native)
    at Function.eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:33785:461)
    at b (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6188:14)
    at a (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6234:18)
    at cljs.core.do_dispatch (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:13583:26)
    at cljs.core.MultiFn.cljs$core$IMultiFn$_dispatch$arity$2 (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:13655:32)
    at cljs.core._dispatch (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:13568:14)
    at a (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:13662:32)
    at b [as call] (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:13666:14)
    at Function.lt.objs.clients.local.__BEH__send_BANG_ (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:33826:43)
```

Using OSX 10.9.1, LightTable 0.6.2

**Comment by mikebelanger** [comment]
@mrcslws @cldwalker Thanks, was stumped on that -- I should read the readme next time.
