### ISSUE TITLE
Cannot double-watch

### ISSUE THREAD

**Issue by johnjelinek** [LightTable/LightTable#1231]
![ltwatch](https://f.cloud.github.com/assets/873610/2060813/024adfe4-8c32-11e3-9260-7f1775eb1a87.gif)

I'd expect to be able to see the value of the reduce and the map.

Here's the console.
```
Invalid behavior: :lt.plugins.clojure.instarepl/on-eval-sonar
TypeError: Cannot read property 'from' of undefined
    at lt.plugins.watches.watched_range (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:31016:270)
    at Function.__BEH__on_eval_sonar (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/clojure_compiled.js:1155:273)
    at c (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6236:18)
    at lt.object.raise_STAR_ (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20513:74)
    at a (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20546:34)
    at b (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20550:14)
    at Function.__BEH__on_eval_one (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/clojure_compiled.js:1159:110)
    at c (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6236:18)
```

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/4 as the instarepl is now its own plugin
