### ISSUE TITLE
OS X + bash-it issue

### ISSUE THREAD

**Issue by andriytyurnikov** [LightTable/LightTable#1277]
```
Error: Error: Command failed: /Users/andriytyurnikov/.bash_it/lib/helpers.bash: line 76: `bash-it': not a valid identifier
is not ISeqable
    at Error (<anonymous>)
    at cljs.core.seq (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2833:11)
    at cljs.core.empty_QMARK_ (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3693:62)
    at eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:30095:32)
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.eval (child_process.js:950:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.eval [as close] (net.js:466:12)
```

**Comment by kenny-evitt** [comment]
@ndr-qef any reason to keep this issue open?

**Comment by BenjaminVanRyseghem** [comment]
ping?

**Comment by kenny-evitt** [comment]
Comment if this should be re-opened.
