### ISSUE TITLE
Open files containing spaces in the path fails.

### ISSUE THREAD

**Issue by fbender** [LightTable/LightTable#1292]
OS X 10.9, LT 0.6.4: Opening file with spaces anywhere in its path (e.g. by double-clicking it in Finder) fails. 

E.g. `/Users/f***********r/Google Drive/H******e I*******nör/Assets/Fonts/Museo/museo.css` yields:
```
"Invalid behavior: :lt.objs.cli/open!"
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at lt.objs.files.resolve (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:21702:30)
    at eval (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:29110:38)
    at eval (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:7612:44)
    at cljs.core.LazySeq.sval (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5561:40)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5571:8)
    at cljs.core._seq (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2311:14)
    at cljs.core.seq (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2824:27)
    at cljs.core.Cons.cljs$core$INext$_next$arity$1 (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5383:51)
    at cljs.core._next (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2008:14)
    at cljs.core.next (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2851:150)
    at cljs.core.LazySeq.cljs$core$INext$_next$arity$1 (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5552:49)
```

Drag & Drop opening works, though. 

(Spun off of issue #1205 comment [35382886](https://github.com/LightTable/LightTable/pull/1205#issuecomment-35382886).)

**Comment by kenny-evitt** [comment]
@cldwalker Thanks!
