### ISSUE TITLE
Can't connect when you have `:eval-in :leiningen` in your project.clj

### ISSUE THREAD

**Issue by mynomoto** [LightTable/LightTable#1316]
In a new project, just adding `:eval-in :leiningen` to project.clj, I got this error:

```
We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:

final project:  {:compile-path /home/y/devel/test/target/classes, :group test, :license {:name Eclipse Public License, :url http://www.eclipse.org/legal/epl-v10.html}, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :repl-options {:init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name test 0.1.0-SNAPSHOT, :project (quote {:compile-path /home/y/devel/test/target/classes, :group test, :license {:name Eclipse Public License, :url http://www.eclipse.org/legal/epl-v10.html}, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :repl-options {:custom-eval (require (quote [fipp.edn :refer (pprint) :rename {pprint fipp}]))}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [slamhound/slamhound 1.5.0 :exclusions ([org.clojure/clojure])] [repetition-hunter/repetition-hunter 1.0.0] [org.clojure/tools.namespace 0.2.4] [fipp/fipp 0.4.1]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path /home/y/devel/test/target, :name test, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root /home/y/devel/test, :offline? false, :source-paths (/home/y/devel/test/src), :certificates [clojars.pem], :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :url http://example.com/FIXME, :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (/home/y/devel/test/dev-resources /home/y/devel/test/resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :leiningen, :plugins ([org.clojure/clojure 1.5.1] [lein-pprint/lein-pprint 1.1.1] [lein-kibit/lein-kibit 0.0.8] [lein-ancient/lein-ancient 0.5.4] [lein-difftest/lein-difftest 2.0.0] [lein-garden/lein-garden 0.1.5] [com.jakemccrary/lein-test-refresh 0.3.9] [codox/codox 0.6.6] [lein-try/lein-try 0.4.1]), :native-path /home/y/devel/test/target/native, :description FIXME: write description, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (/home/y/devel/test/test), :clean-targets [:target-path], :aliases {slamhound [run -m slam.hound]}})}), :nrepl-middleware [lighttable.nrepl.handler/lighttable-ops], :custom-eval (require (quote [fipp.edn :refer (pprint) :rename {pprint fipp}]))}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [slamhound/slamhound 1.5.0 :exclusions ([org.clojure/clojure])] [repetition-hunter/repetition-hunter 1.0.0] [org.clojure/tools.namespace 0.2.4] [fipp/fipp 0.4.1] [lein-light-nrepl/lein-light-nrepl 0.0.16] [org.clojure/tools.reader 0.8.3]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path /home/y/devel/test/target, :name test, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root /home/y/devel/test, :offline? false, :source-paths (/home/y/devel/test/src), :certificates [clojars.pem], :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :url http://example.com/FIXME, :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (/home/y/devel/test/dev-resources /home/y/devel/test/resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :leiningen, :plugins ([org.clojure/clojure 1.5.1] [lein-pprint/lein-pprint 1.1.1] [lein-kibit/lein-kibit 0.0.8] [lein-ancient/lein-ancient 0.5.4] [lein-difftest/lein-difftest 2.0.0] [lein-garden/lein-garden 0.1.5] [com.jakemccrary/lein-test-refresh 0.3.9] [codox/codox 0.6.6] [lein-try/lein-try 0.4.1]), :native-path /home/y/devel/test/target/native, :description FIXME: write description, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (/home/y/devel/test/test), :clean-targets [:target-path], :aliases {slamhound [run -m slam.hound]}}
java.lang.IllegalStateException: Can't change/establish root binding of: *warn-on-reflection* with set
	at clojure.lang.Var.set(Var.java:233)
	at clojure.core$eval22.invoke(NO_SOURCE_FILE)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.eval(Compiler.java:6582)
	at clojure.core$eval.invoke(core.clj:2852)
	at leiningen.core.eval$fn__3577.invoke(eval.clj:304)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
	at clojure.lang.AFn.applyToHelper(AFn.java:167)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:619)
	at leiningen.repl$repl.doInvoke(repl.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at leiningen.light_nrepl.main(Unknown Source)
```

**Comment by cldwalker** [comment]
Moved to https://github.com/LightTable/Clojure/issues/65
