### ISSUE TITLE
Unable to evaluate function with ^:export annotation in ClojureScript

### ISSUE THREAD

**Issue by rspacjer** [LightTable/LightTable#1443]
I have simple function:
```
(defn ^:export sample-number [] 1)
```
when I try to evaluate it in LightTable I got such error:
```
#<SyntaxError: Unexpected identifier>
SyntaxError: Unexpected identifier
    at eval (native)
    at SocketNamespace.<anonymous> (http://localhost:56003/socket.io/lighttable/ws.js:118:26)
    at SocketNamespace.EventEmitter.emit [as $emit] (http://localhost:56003/socket.io/socket.io.js:633:15)
    at SocketNamespace.onPacket (http://localhost:56003/socket.io/socket.io.js:2248:20)
    at Socket.onPacket (http://localhost:56003/socket.io/socket.io.js:1930:30)
    at Transport.onPacket (http://localhost:56003/socket.io/socket.io.js:1332:17)
    at Transport.onData (http://localhost:56003/socket.io/socket.io.js:1303:16)
    at WebSocket.websocket.onmessage (http://localhost:56003/socket.io/socket.io.js:2378:12)
```

When I remove the ^:export annotation then I can evaluate it without any problem.

There is similar error: https://github.com/LightTable/LightTable/issues/484 marked as fixed, but I can still reproduce it.

Light Table version
0.6.5
Binary version
0.8.4

I'm working on the Windows 8.1 machine

**Comment by cldwalker** [comment]
Now that LT supports a modern version of ClojureScript, this won't be an issue for any givencljs  project. If you want to connect to the Light Table UI connection, this won't work until we update clojurescript which is being tracked in #1973
