### ISSUE TITLE
typing toString in Haskell tab gives strange behavior

### ISSUE THREAD

**Issue by flashus** [LightTable/LightTable#1493]
When typing "toString" (without quotes, with quotes its fine) on Haskell tab, I get lags and cannot type anything, when switching to other tab and back, Haskell tab is black and no text shown. When I press ctrl+z to untype last letter it's fine again. In the console I have error messages:

```
"Invalid behavior: :lt.objs.editor/refresh-on-show"
TypeError: Object function toString() { [native code] } has no method 'match'
    at extractLineClasses (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:5587:28)
    at runMode (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:5628:17)
    at highlightLine (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:5657:5)
    at getLineStyles (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:5692:20)
    at buildLineContent (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:5750:40)
    at getLineContent (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:833:12)
    at buildLineElement (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:903:17)
    at patchDisplay (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:764:20)
    at updateDisplayInner (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:644:5)
    at updateDisplay (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:556:12)
    at endOperation (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:1941:21)
    at eval [as refresh] (C:%5Csrc%5CLightTable%5Cdeploy%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:2019:17)
```

**Comment by cldwalker** [comment]
We've released 0.8.0-alpha! - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Ping us if it is still an issue
