### ISSUE TITLE
Error on launch even after a clean install on Mac OS X

### ISSUE THREAD

**Issue by tbassetto** [LightTable/LightTable#1498]
I am using Max OS 10.9.3 and LightTable 0.6.6. When I launch it I have a small red rectangle at the bottom. When clicking on it it expands a panel and displays the following error:

```
Error: Error: Command failed: is not ISeqable
    at Error (<anonymous>)
    at cljs.core.seq (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2833:11)
    at cljs.core.empty_QMARK_ (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3693:62)
    at eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:30551:32)
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.eval (child_process.js:950:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.eval [as close] (net.js:466:12)
```

I tried to find the cause on the web but no luck. I am the only one seeing this?

**Comment by sidcarter** [comment]
Had the same problem. Removing stuff in my .profile fixed it for me. Weird!

**Comment by kenny-evitt** [comment]
It seems likely these errors are due to ["bash identifiers containing hyphens because, strictly speaking, they are illegal in bash"](https://github.com/LightTable/LightTable/issues/1277#issuecomment-36441727).

@sidcarter Do you see "Failed to source PATH files. See console log for details." in the bottom status bar when you get this error? I just want to confirm that the changes made by [this PR](https://github.com/LightTable/LightTable/pull/1205) are logging this error.

**Comment by sidcarter** [comment]
This is what was there in my .profile:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```

And these are the exact messages in the console:

```
Error: Error: Command failed: is not ISeqable
    at Error (<anonymous>)
    at cljs.core.seq (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2833:11)
    at cljs.core.empty_QMARK_ (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3693:62)
    at eval (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:31483:32)
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.eval (child_process.js:950:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.eval [as close] (net.js:466:12)
```

Don't see anything else in the bottom status bar. I'm using:

Light Table version
0.7.2
Binary version
0.8.4
