### ISSUE TITLE
Instarepl clojure does not connect

### ISSUE THREAD

**Issue by nsfan** [LightTable/LightTable#1717]
Hello! 

LightTable 0.6.7
JDK 1.7.72 x64
Win7 64bit

I am newbie with clojure. I tried instarepl, but it went a never ending cycle.
It wrote on console : "connecting" and then "retrieving deps" but the loading never finished.

I see that (in taskmanager) it starts to java process:
1. java -classpath lighttable\plugins\clojure\runner\resources and its sub directories
it takes 400MB memory (taskmanager does not show wich jar or class running)
2. java -Xmx1g -jar ...runner\target\lein-light-standalone.jar LightTable-REPL
it takes 350MB

When I write something in repl, like: <code>((fn [arg](println arg)) "hello")</code> - it is a function which println its arg parameter
It starts 2 new process in the same way (like I wrote before) It takes 750MB again.
And the old java processes also run. So it takes 1,5GB memory and the loading still under process.
Then my PC had not enough memory for this.

Once I got this message:

```
We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:
final project:  {:compile-path I:\clojure\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :repl-options {:nrepl-middleware [lighttable.nrepl.handler/lighttable-ops], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name LightTable-REPL, :project (quote {:compile-path I:\clojure\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path I:\clojure\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root I:\clojure\LightTable\plugins\clojure\runner\resources, :offline? false, :source-paths (I:\clojure\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (I:\clojure\LightTable\plugins\clojure\runner\resources\dev-resources I:\clojure\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins [], :native-path I:\clojure\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (I:\clojure\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]})})}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.0.18] [org.clojure/tools.reader 0.8.3]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path I:\clojure\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root I:\clojure\LightTable\plugins\clojure\runner\resources, :offline? false, :source-paths (I:\clojure\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (I:\clojure\LightTable\plugins\clojure\runner\resources\dev-resources I:\clojure\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins [], :native-path I:\clojure\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (I:\clojure\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]}
Error occurred during initialization of VM
Could not reserve enough space for object heap
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)

    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.repl$repl.doInvoke(repl.clj:261)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at leiningen.light_nrepl.main(Unknown Source)
```

**Comment by rhlvora** [comment]
If it helps, I just installed jdk8-u45 64 bit on windows 7 and it is working.

**Comment by kenny-evitt** [comment]
@rhlvora thanks!
