### ISSUE TITLE
Show docs breaks instarepl on windows

### ISSUE THREAD

**Issue by joshuafcole** [LightTable/LightTable#1732]
I was recently walking a friend through generating music algorithmically in overtone. On introducing him to LT's instarepl for him to start writing some code, we found that the show docs function was generating 40 lines of error stack trace. This seems related to a previous issue involving temp file creation that I can't seem to find right now. The instarepl works fine normally before show docs is used. We used it on a regular function (in this case `+`). I can continue working with him to provide more diagnostic information.
```
OS: Win7x64
Version: 0.7.1
Clojure: 0.1.0
```

Repro:
```
1. Open new instarepl
2. Type `(+ 1 2)` works fine
3. Mouse click on `+`
4. ctrl-d to show docs
5. Check console for errors
```

Stack Trace:
```
java.io.IOException: The system cannot find the path specified
at java.io.WinNTFileSystem.createFileExclusively(Native Method)
at java.io.File.createTempFile(File.java:1879)
at java.io.File.createTempFile(File.java:1923)
at lighttable.nrepl.doc$jar_url__GT_file.invoke(doc.clj:59)
at lighttable.nrepl.doc$resolve_file.invoke(doc.clj:76)
at clojure.lang.AFn.applyToHelper(AFn.java:161)
at clojure.lang.AFn.applyTo(AFn.java:151)
at clojure.core$apply.invoke(core.clj:619)
at clojure.core$update_in.doInvoke(core.clj:5587)
at clojure.lang.RestFn.invoke(RestFn.java:445)
at lighttable.nrepl.doc$eval5979$fn__5981.invoke(doc.clj:116)
at clojure.lang.MultiFn.invoke(MultiFn.java:227)
at lighttable.nrepl.core$queued$fn__1851.invoke(core.clj:98)
at clojure.core$comp$fn__4154.invoke(core.clj:2330)
at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__635.invoke(interruptible_eval.clj:138)
at clojure.lang.AFn.run(AFn.java:24)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)
```

**Comment by dxlr8r** [comment]
@jdwaterson thank you :+1:

**Comment by martinchooooooo** [comment]
Can confirm that I was having the same issue and I had tried (before reading this issue) the same approach of upgrading from JDK 7 to JDK 8 and it seemed to have fixed my issue,

**Comment by kenny-evitt** [comment]
@joshuafcole @cldwalker could either or both of you confirm whether this is resolved by upgrading the JDK to version 8?

**Comment by acceleanu** [comment]
I had the same issue on a mac. Switched to Java 8 and that resolved it. A nice way to manage multiple versions of java is by using http://www.jenv.be .

**Comment by cldwalker** [comment]
Apologies for getting back to this thread late. Too many issues and too small of a core team. As you all have discovered jump to source targeted Java 8. The Clojure plugin will no longer support Java 7 as Oracle [hasn't supported it since April of this year](http://www.oracle.com/technetwork/java/javase/downloads/eol-135779.html). I've updated the Clojure plugin to reflect this - https://github.com/LightTable/Clojure/commit/ae403834f63c3c74bbfa20a0de2307dd82be09e3
