### ISSUE TITLE
console.log  broken on NodeJs connection 

### ISSUE THREAD

**Issue by jhnstn** [LightTable/LightTable#1746]
This is on 0.7.2 

With a nodejs connection, `console.log('foo')` is raising : 

```
Invalid behavior: :lt.plugins.js.node/on-out
Error: Invalid arity: 1
    at Error (<anonymous>)
    at a (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:27580:11)
    at Function.__BEH__on_out (/Users/jason/Projects/LightTable/deploy/plugins/javascript/javascript_compiled.js:56:130)
    at c (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20477:18)
    at a (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20488:34)
    at b (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20492:14)
    at Socket.eval (file:///Users/jason/Projects/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:31405:78)
```

**Comment by jyounus** [comment]
I'm new to LightTable and I have the same issue. I just downloaded the latest version from the website but I still get the same error. How do I update the Javascript plugin?

**Comment by kenny-evitt** [comment]
@jyounus type "plugin manager" in the command box – the full command is *Plugins: Show plugin manager*. When you hover over the JavaScript plugin in the list there should be three buttons on the right – *uninstall*, *source*, and *update*. Click *update*.

**Comment by jyounus** [comment]
There was no update button for Javascript. I had to uninstall and reinstall the plugin. It was on version 0.0.6 before. Now I'm on 0.1.2 and I'm not getting the error anymore. Thanks for your help kenny-evitt! :)

**Comment by kenny-evitt** [comment]
@jyounus – glad it's working for you now.
