### ISSUE TITLE
Advanced find (x-workspace) causes ongoing fauls

### ISSUE THREAD

**Issue by statler** [LightTable/LightTable#1765]
using the ctrl+shft+f find across the workspace finds expected results, but then the function does not complete.

After doing a search, actions on some editor activities produce errors in the console such as below, but still seem to work

```
Invalid behavior: :lt.objs.thread/send!
Error: channel closed
    at ChildProcess.target.send (child_process.js:402:26)
    at Function.lt.objs.thread.__BEH__send_BANG_ (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:31527:132)
    at c (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:20477:18)
    at a (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:20488:34)
    at b (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:20492:14)
    at Function.lt.objs.thread.__BEH__try_send (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:31519:279)
    at c (file:///C:/Users/denni_000/Documents/java_apps/LightTable/core/node_modules/lighttable/bootstrap.js:6196:14)
```

**Comment by cldwalker** [comment]
Closing as no one has shown interest on working on this and it's not a common use case. When I've worked on software projects that are > 1GB I make sure that my [ignore pattern](https://github.com/LightTable/LightTable/blob/e80f1b928890a702f53d519305ebe4b0c2982837/src/lt/objs/files.cljs#L43-L51) ignores most large blobs and then I don't have any issues searching. I'd recommend [my smart-ignore plugin](https://github.com/cldwalker/smart-ignore) which automatically sets this based on a .gitignore
