### ISSUE TITLE
Gherkin syntax is not working

### ISSUE THREAD

**Issue by cneira** [LightTable/LightTable#1795]
It fails with the following error

```
Error: Mode gherkin failed to advance stream.
    at readToken (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:5966:11)
    at runMode (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:6006:36)
    at highlightLine (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:6038:5)
    at getLineStyles (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:6073:20)
    at buildLineContent (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:6133:40)
    at getLineContent (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:929:12)
    at buildLineElement (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:1002:17)
    at patchDisplay (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:860:20)
    at updateDisplayIfNeeded (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:711:5)
    at endOperation_W1 (C:%5CUsers%5Ca03550a%5CDesktop%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Ccodemirror.js:2145:42)
```

**Comment by cldwalker** [comment]
@cneira No need to create your own plugin. Latest LightTable comes with gherkin mode but we haven't defined the file type yet. Add this to your user.behaviors:

```clj
 [:files :lt.objs.files/file-types [{:exts [:feature], :mime "text/x-feature", :tags [:editor.gherkin], :name "gherkin"}]]
```

I'll add this definition on master so the next release doesn't have this issue
