### ISSUE TITLE
Can't eval due to missing standalone jar

### ISSUE THREAD

**Issue by justintaft** [LightTable/LightTable#1832]
Lighttable needs lein-light-standalone.jar in order to eval. 
`lein uberjar` creates the file
`lein install` does not, but also removes the standalone jar.

lighttable/clojure.sh runs `lein uberjar` then `lein install`.
https://github.com/LightTable/Clojure/blob/master/build.sh

I am using the master branch (node).

For people who are running into  the below message while evaling (will show under console), cd to
`deploy/plugins/clojure` and run `lein uberjar`. Evaling in light table should work then.

```
Invalid behavior: :lt.plugins.clojure/eval!
TypeError: Cannot call method 'call' of undefined
    at notify (/Users/justintaft/programming/LightTable/deploy/plugins/clojure/clojure_compiled.js:1243:24)
    at check_all (/Users/justintaft/programming/LightTable/deploy/plugins/clojure/clojure_compiled.js:1258:83)
    at try_connect (/Users/justintaft/programming/LightTable/deploy/plugins/clojure/clojure_compiled.js:326:38)
    at lt.objs.eval.find_client (file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:30817:16)
    at lt.objs.eval.get_client_BANG_ (file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:30844:32)
    at Function.__BEH__eval_BANG_ (/Users/justintaft/programming/LightTable/deploy/plugins/clojure/clojure_compiled.js:399:69)
    at c (file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:20477:18)
```

```
justins-MacBook-Pro:clojure justintaft$ sh build.sh 
Compiling leiningen.light-nrepl
Warning: skipped duplicate file: project.clj
Created /Users/justintaft/programming/LightTable/deploy/plugins/clojure/runner/target/lein-light-0.1.0.jar
Created /Users/justintaft/programming/LightTable/deploy/plugins/clojure/runner/target/lein-light-standalone.jar
Compiling leiningen.light-nrepl
Warning: skipped duplicate file: project.clj
Created /Users/justintaft/programming/LightTable/deploy/plugins/clojure/runner/target/lein-light-0.1.0.jar
Wrote /Users/justintaft/programming/LightTable/deploy/plugins/clojure/runner/pom.xml
Installed jar and pom into local repo.
Created /Users/justintaft/programming/LightTable/deploy/plugins/clojure/lein-light-nrepl/target/lein-light-nrepl-0.1.0.jar
Wrote /Users/justintaft/programming/LightTable/deploy/plugins/clojure/lein-light-nrepl/pom.xml
Installed jar and pom into local repo.
 --- Done!
```

**Comment by justintaft** [comment]
https://github.com/LightTable/Clojure/blob/f49cf54420106b1c7cd43c8667f420b58830e7d7/src/lt/plugins/clojure.cljs#L855
function `deploy/deploy` doesn't exist. Was this supposed to fetch the standalone jar?

**Comment by cldwalker** [comment]
@justintaft Good catch on deploy/deploy. It used to refer to [this](https://github.com/LightTable/LightTable/blob/296dedb97d3e06a709854284bdf2f59b4b03dac1/src/lt/objs/deploy.cljs#L117-L126) but was removed [some time ago](https://github.com/LightTable/LightTable/commit/9c283d003d00fdb2d74e8ca5117e6ecfcd559144#diff-a27d831e5730304bc2b99611ccb6b7bb)
@ibdknox Thoughts on what do about an old reference to deploy/deploy? Not familiar with what $LTLOCAL did

**Comment by kenny-evitt** [comment]
@justintaft I'm closing this because the active working branch is now *atom-shell*.
