### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by ath** [LightTable/LightTable#1836]
Using Light Table version 0.7.2 (Binary version 0.8.6) on Windows 7.
Maybe not really useful bug report, but here it comes anyway: I was playing around with tabsets, but can’t say what exactly produced the error. I noticed a red `2` in the lower right corner, and when I clicked it this message on red background popped up:

```
TypeError: Cannot call method 'call' of null
    at lt.object.has_tag_QMARK_ (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:20799:128)
    at Function.lt.objs.style.__BEH__remove_theme (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:30065:52)
    at c (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:20477:18)
    at a (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:20488:34)
    at b (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:20492:14)
    at lt.object.destroy_BANG_ (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:20731:49)
    at Function.lt.objs.editor.__BEH__destroy_on_close (file:///C:/Users/athieme/LightTable/core/node_modules/lighttable/bootstrap.js:24315:34)
```

**Comment by cldwalker** [comment]
Thanks for the stacktrace but we do need bugs to [be reproducible](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs). Judging from the stacktrace it seems a theme was being removed and there was no active tab. If you can get us some reproducible steps that would be great. If not I'll close in a few days

**Comment by cldwalker** [comment]
Closing. Feel free to provide reproducible steps and we can reopen
