### ISSUE TITLE
Cannot connect to any clojure project: java.lang.ClassNotFoundException: lighttable.nrepl.core

### ISSUE THREAD

**Issue by ArturSkowronski** [LightTable/LightTable#1848]
I cannot connect to any Clojure project from LightTable. I only have stacktrace which not say much. (I'm new for clojure and it look like really generic one)
 
```
final project:  {:compile-path /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/target/classes, :group testing-lighttable, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name testing-lighttable 0.1.0-SNAPSHOT, :project (quote {:compile-path /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/target/classes, :group testing-lighttable, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}}, :dependencies ([org.clojure/clojure 1.6.0] [compojure/compojure 1.1.6] [hiccup/hiccup 1.0.5] [ring-server/ring-server 0.3.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [ring-mock/ring-mock 0.1.5] [ring/ring-devel 1.3.1] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.1.9] [jonase/eastwood 0.2.1]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/target, :name testing-lighttable, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable, :offline? false, :source-paths (/Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/src), :certificates [clojars.pem], :ring {:destroy testing-lighttable.handler/destroy, :init testing-lighttable.handler/init, :handler testing-lighttable.handler/app}, :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :profiles {:production {:ring {:stacktraces? false, :auto-reload? false, :open-browser? false}}, :uberjar {:aot :all}, :dev {:dependencies [[ring-mock 0.1.5] [ring/ring-devel 1.3.1]]}}, :prep-tasks [javac compile], :url http://example.com/FIXME, :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (/Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/dev-resources /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([lein-ring/lein-ring 0.8.12] [venantius/ultra 0.1.9]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/target/native, :description FIXME: write description, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (/Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/test), :clean-targets [:target-path]})})}, :dependencies ([org.clojure/clojure 1.6.0] [compojure/compojure 1.1.6] [hiccup/hiccup 1.0.5] [ring-server/ring-server 0.3.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [ring-mock/ring-mock 0.1.5] [ring/ring-devel 1.3.1] [lein-light-nrepl/lein-light-nrepl 0.1.0] [org.clojure/tools.reader 0.8.3] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.1.9] [jonase/eastwood 0.2.1]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/target, :name testing-lighttable, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable, :offline? false, :source-paths (/Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/src), :certificates [clojars.pem], :ring {:destroy testing-lighttable.handler/destroy, :init testing-lighttable.handler/init, :handler testing-lighttable.handler/app}, :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :profiles {:production {:ring {:stacktraces? false, :auto-reload? false, :open-browser? false}}, :uberjar {:aot :all}, :dev {:dependencies [[ring-mock 0.1.5] [ring/ring-devel 1.3.1]]}}, :prep-tasks [javac compile], :url http://example.com/FIXME, :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (/Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/dev-resources /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([lein-ring/lein-ring 0.8.12] [venantius/ultra 0.1.9]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path /Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/target/native, :description FIXME: write description, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (/Users/arturskowronski/Priv/Playground/Clojure/testing-lighttable/test), :clean-targets [:target-path]}
Exception in thread "main" java.lang.ClassNotFoundException: lighttable.nrepl.core, compiling:(/private/var/folders/kv/qnw3b8g10333ztfsd73_st5r0000gn/T/form-init6994458491899885360.clj:1:1063)
	at clojure.lang.Compiler.analyze(Compiler.java:6464)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.eval(Compiler.java:6700)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: lighttable.nrepl.core
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at clojure.lang.RT.classForName(RT.java:2065)
	at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:978)
	at clojure.lang.Compiler$HostExpr.access$400(Compiler.java:756)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6832)
	at clojure.lang.Compiler.analyze(Compiler.java:6427)
	... 25 more
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invoke(core.clj:4327)
	at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
	at clojure.lang.AFn.applyToHelper(AFn.java:167)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:619)
	at leiningen.repl$repl.doInvoke(repl.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at leiningen.light_nrepl.main(Unknown Source)
```
If I try to do anything from the Lein, everything is ok.

OS: OSX Yosemite
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Leiningen 2.5.0 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM

**Comment by justintaft** [comment]
Not sure if related, #1832  might help...

**Comment by ArturSkowronski** [comment]
Thanks for a hint. I created and installed uberjar right now and it succeded. Unfortunatelly, I still have the same problem with connection.

**Comment by ArturSkowronski** [comment]
The same problem is with InstaREPL:
````
final project:  {:compile-path /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/target/classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name LightTable-REPL, :project (quote {:compile-path /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/target/classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.1.9] [jonase/eastwood 0.2.1]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources, :offline? false, :source-paths (/Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (/Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/dev-resources /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([venantius/ultra 0.1.9]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/target/native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (/Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/test), :clean-targets [:target-path]})})}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.1.0] [org.clojure/tools.reader 0.8.3] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.1.9] [jonase/eastwood 0.2.1]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources, :offline? false, :source-paths (/Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (/Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/dev-resources /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([venantius/ultra 0.1.9]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path /Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/target/native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (/Users/arturskowronski/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/runner/resources/test), :clean-targets [:target-path]}
Exception in thread "main" java.lang.ClassNotFoundException: lighttable.nrepl.core, compiling:(/private/var/folders/kv/qnw3b8g10333ztfsd73_st5r0000gn/T/form-init3508514336629643507.clj:1:1063)
	at clojure.lang.Compiler.analyze(Compiler.java:6380)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.eval(Compiler.java:6616)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: lighttable.nrepl.core
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at clojure.lang.RT.classForName(RT.java:2070)
	at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:969)
	at clojure.lang.Compiler$HostExpr.access$400(Compiler.java:747)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6766)
	at clojure.lang.Compiler.analyze(Compiler.java:6343)
	... 25 more
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invoke(core.clj:4327)
	at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
	at clojure.lang.AFn.applyToHelper(AFn.java:167)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:619)
	at leiningen.repl$repl.doInvoke(repl.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at leiningen.light_nrepl.main(Unknown Source)

````

**Comment by stephenmuss** [comment]
I'm also experiencing this.

**Comment by damacisaac** [comment]
same problem here

**Comment by podviaznikov** [comment]
have the same problem

**Comment by codesplicer** [comment]
I'm experiencing the same problem too

LightTable v0.7.2
OS: OSX Yosemite 10.10.2
Leiningen 2.5.0 on Java 1.7.0_17

**Comment by acron0** [comment]
Same problem here

LightTable v0.7.2
OS: Windows 8.1
Leiningen 2.5.1 on Java 1.8.0_31 Java HotSpot(TM) Client VM

**Comment by acron0** [comment]
My project.clj:

    (defproject tbserver "0.0.1-SNAPSHOT"
      :description "TBServer"
      :dependencies [[org.clojure/clojure "1.6.0"]
  	                 [org.clojure/data.json "0.2.6"]
  				     [com.taoensso/timbre "3.4.0"]
                     [io.netty/netty "3.6.3.Final"]
                     [ring/ring-jetty-adapter "1.3.2"]
                     [compojure "1.3.2"]
                     [selmer "0.8.2"]]
      :main tbserver.core)

**Comment by lambdahands** [comment]
Hi, after some digging in Google Groups, I found the solution to this problem.

It turns out the [Ultra leiningen plugin](https://github.com/venantius/ultra) was interfering with the LightTable REPL. If you open your `~/.lein/profiles.clj` and upgrade Ultra to the latest version (as of now it's `0.3.3`), this problem will go away.

[Related issue on the Ultra project](https://github.com/venantius/ultra/issues/19)

I've also added this information to the [Debugging Issues Wiki Section](https://github.com/LightTable/LightTable/wiki/Debugging-Issues). If it doesn't belong there, let me know, and I can move it to a better place.

Thanks!

**Comment by acron0** [comment]
@lambdahands Thank you! Can confirm, this fixed it for me!

**Comment by ArturSkowronski** [comment]
Perfect! Thank You!


— Artur Skowroński

**Comment by stephenmuss** [comment]
Works for me now too. Thank you!

**Comment by codesplicer** [comment]
Fixed for me too! Thanks!

**Comment by rundis** [comment]
Great stuff. Tx @lambdahands.
I take it this can be closed then
