### ISSUE TITLE
Unable to edit file directly from FTP client

### ISSUE THREAD

**Issue by Eevets** [LightTable/LightTable#1849]
Hi, 
I am on Mac, I've configure my FTP client to open file with Light Table, but I got the following error if I open the file. seems similar with the older ticket about drag and drop file to Light Table. Thanks.

TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at lt.objs.files.resolve (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:21718:30)
    at eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:30431:38)
    at eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:7612:44)
    at cljs.core.LazySeq.sval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5561:40)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5571:8)
    at cljs.core._seq (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2311:14)
    at cljs.core.seq (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2824:27)
    at cljs.core.Cons.cljs$core$INext$_next$arity$1 (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5383:51)
    at cljs.core._next (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2008:14)

**Comment by Eevets** [comment]
btw, I am using Light Table 0.7.2

**Comment by cldwalker** [comment]
This seems to be an issue because the ftp client is passing multiple files which our node-webkit event handlers don't seem to handle. On our atom-shell this has been improved and I can open ftp files with cyberduck. Marking as fixed since atom-shell will go out on the next release

**Comment by Eevets** [comment]
Ok. Thank you so much.

anyway, for your info. I was using Transmit.
