### ISSUE TITLE
Obscure error on first run

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [LightTable/LightTable#1860]
I'm getting a red ‘1’ in the bottom-left (which, by the way, has non-obvious meaning to a new user like myself). Clicking it, it becomes clear that I'm getting the following error when I boot up LightTable:

```
Error: Error: Command failed: stty: stdin isn't a terminal
is not ISeqable
    at Error (<anonymous>)
    at cljs.core.seq (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2833:11)
    at cljs.core.empty_QMARK_ (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3693:62)
    at eval (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:31483:32)
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.eval (child_process.js:950:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.eval [as close] (net.js:466:12)
```

**Comment by cldwalker** [comment]
Hi. Thanks for the bug report but this is not reproducible for a standard install. To narrow down if this is an issue specific to the LT cask, install LT from its homepage. If it's still an issue, please [provide reproducible steps](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs) e.g. run from the commandline or from Finder, what args, what plugins do you have installed, etc.

**Comment by ELLIOTTCABLE** [comment]
I'll take a look at this soon! Thanks for the replies (on this, and other issues), @cldwalker. <3
