### ISSUE TITLE
No available plugins for Yosemite

### ISSUE THREAD

**Issue by Kindpire** [LightTable/LightTable#1863]
Hi,
I'm using Yosemite 10.10.2, when I opened plugin managers, there is nothing in the available plugins, and after a while, it showed some errors:

```
Error: ENOENT, no such file or directory '/Users/pengfei/Library/Application Support/LightTable/metadata-temp'
    at Object.fs.readdirSync (fs.js:654:18)
    at lt.objs.files.full_path_ls (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:21917:134)
    at Extract.eval (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:29195:69)
    at Extract.EventEmitter.emit (events.js:117:20)
    at DirWriter.eval (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/tar/lib/extract.js:66:8)
    at DirWriter.EventEmitter.emit (events.js:117:20)
    at end (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/tar/node_modules/fstream/lib/writer.js:323:12)
    at eval (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/tar/node_modules/fstream/lib/writer.js:313:32)
    at endUtimes (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/tar/node_modules/fstream/lib/writer.js:239:48)
    at setProps (/Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/tar/node_modules/fstream/lib/writer.js:296:5)

Error: ENOENT, lstat '/Users/pengfei/Library/Application Support/LightTable/metadata-temp'
```

Any idea?

**Comment by Announcement** [comment]
Plugins aren't available yet anywhere :(

**Comment by Kindpire** [comment]
But it works when I ran it on Windows 7.

**Comment by BenjaminVanRyseghem** [comment]
work to me on Yosemite 10.10.4 on the `atom-shell` branch

**Comment by kenny-evitt** [comment]
@Kindpire @Announcement If you could, please try running the latest source version of LT. We just merged the *atom-shell* branch into *master* so build the latter to get the most recent changes.

There also seems to be an open issue with some plugins and the GitHub Git repo URLs they use – see PR #1937. If you observe errors installing a plugin, merge the changes in that PR into your local LT repo and try installing those plugins again.

**Comment by Kindpire** [comment]
Thanks all your help!
