### ISSUE TITLE
Program does not exectue in console

### ISSUE THREAD

**Issue by diamondjozu** [LightTable/LightTable#1865]
Hi,

For a while now i've had various problems with lighttable ( i used to have to in super user to launch it).

However now whenever i try execute a program in the console tab the system simply just does not respond, furthermore everytime i launch lighttable i am presented with this error below in the console which I do not understand.

Invalid behavior: :lt.objs.workspace/reconstitute-last-workspace
Error: EOF while reading
    at Error (<anonymous>)
    at a (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:22106:11)
    at b (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:22110:14)
    at cljs.reader.read (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:22412:61)
    at cljs.reader.read_string (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:22433:27)
    at lt.objs.workspace.file__GT_ws (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:27296:61)
    at eval (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:7612:44)
    at cljs.core.LazySeq.sval (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:5561:40)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:5571:8)
    at cljs.core._seq (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:2311:14)
    at cljs.core.LazySeq.cljs$core$ISeq$_first$arity$1 (file:///opt/LightTable/core/node_modules/lighttable/bootstrap.js:5584:18)

**Comment by cldwalker** [comment]
Hi. The console is a read-only tab so there isn't a way to execute a program in it. That error comes from LightTable trying to read an invalid cache file on startup. I'm guessing the invalid cache was created by permissions issues from running as a superuser. I would recommend deleting your cache workspace directory. On osx this would be `~/Library/Application\ Support/LightTable/ltcache`. I'm guessing you're on linux so this should be under ~/.config or /opt/LightTable. Feel free to ping here or on the [mailing list](https://groups.google.com/forum/#!forum/light-table-discussion) for more questions.
