### ISSUE TITLE
Warnings when running with XMonad in NixOS

### ISSUE THREAD

**Issue by danbst** [LightTable/LightTable#1869]
```
[danbst@master:~]$ lighttable
[2820:0304/222735:ERROR:browser_main_loop.cc(226)] Gdk: gdk_window_set_icon_list: icons too large
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[2851:0304/222736:ERROR:sandbox_linux.cc(142)] InitializeSandbox() called with multiple threads in process gpu-process
```

Errors in Console:

```
Error: spawn ENOENT
    at errnoException (child_process.js:982:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
thread[stderr]:	
execvp(): No such file or directory

```

Any ways to debug?

**Comment by cldwalker** [comment]
Sorry for the delayed response. There isn't enough information to reproduce your issue. Feel free to try the latest LT, describe what you're doing and provide a full stacktrace

**Comment by cldwalker** [comment]
Closing as there isn't enough info to reproduce. Can reopen if given the above

**Comment by danbst** [comment]
confirm, lighttable 0.8.1 hasn't this issue
