### ISSUE TITLE
regex bug for replace

### ISSUE THREAD

**Issue by Mouvedia** [LightTable/LightTable#1874]
When I use `/\S+(?=[	])/` as the regex and `"$0"` as the replacement nothing happens.

**Comment by kenny-evitt** [comment]
I think you need to use `"$1" as the replacement. From the Java doc page [Matcher (Java Platform SE 7 )](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#group(int)) for the `public String group(int group)` method [emphasis mine]:

> Capturing groups are indexed from left to right, starting at one. **Group zero denotes the entire pattern**, so the expression m.group(0) is equivalent to m.group().

**Comment by Mouvedia** [comment]
@kenny-evitt Did you try it? It's not working either.
I checked with another IDE before posting an issue.

**Comment by kenny-evitt** [comment]
I didn't try it. I'm playing with your regex now in various online testers, but I'm not sure what you're trying to accomplish. If you use `"$0"` as the replacement, then nothing should change. If you use `"$1"`, as I suggested, nothing should happen either – or maybe an error should be shown! – because `(?=[ ])` isn't a capturing group as I initially interpreted.

Would you provide an example of text for which you want to perform this replacement, both before and after the replacement is made?

What other IDE did you check? I'm guessing that you're implying that the replacement works in that other IDE – am I right, did it indeed work?

**Comment by Mouvedia** [comment]
@kenny-evitt The double quotes are part of the code so I am just surrounding the selections with them.

**Comment by kenny-evitt** [comment]
One problem might be that Light Table seems to convert tabs to spaces automatically, tho I'm pretty sure that's configurable, so it may not be doing so for you.

Regardless, I added the following to a file open in Light Table:

```
thisIsSelected  this is not
```

`thisIsSelected` is highlighted when I enter `/\S+(?=[ ]{2})/` in the find field. When I enter `"$0"` in the replace field I get two errors logged to the console:

```
Invalid behavior: :lt.objs.find/replace!
TypeError: Cannot read property '0' of null
    at eval (C:%5CUsers%5Ckevitt%5CDocuments%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Csearch.js:141:75)
    at String.replace (native)
    at Object.replace (C:%5CUsers%5Ckevitt%5CDocuments%5CLightTable%5Ccore%5Cnode_modules%5Ccodemirror%5Csearch.js:141:29)
    at Function.lt.objs.find.__BEH__replace_BANG_ (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:32329:23)
    at c (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:20477:18)
    at a (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:20488:34)
    at b (file:///C:/Users/kevitt/Documents/LightTable/core/node_modules/lighttable/bootstrap.js:20492:14)
```

I'm just guessing, but it seems like the regex and match data isn't available to the replace command.

I'll look into this further and let you know what I find.

**Comment by BenjaminVanRyseghem** [comment]
Can be reproduced in the `atom-shell` branch

**Comment by kenny-evitt** [comment]
This isn't so much a bug as a missing feature. I vaguely remember looking at the relevant code and I think my guess was correct; the replace function can't access the regex match data.

**Comment by Mouvedia** [comment]
If I am matching something then it should replace accordingly. How is that not bug?
Sorry to be blunt, but I am missing your point.

**Comment by kenny-evitt** [comment]
@Mouvedia No worries about being blunt. The relevant code is in a library and the version we're using doesn't seem to implement regexes for replace. I'd like to look at this further when I have time but currently we're focused on finishing the release of version 0.8.0. Pull requests are welcome!

**Comment by kenny-evitt** [comment]
[Here's the relevant LT code.](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/search.cljs#L22-L40)

[That code uses a vendored (and probably forked) Node module `replace`.](https://github.com/LightTable/LightTable/tree/master/deploy/core/node_modules/replace)

**Comment by kenny-evitt** [comment]
I was wrong about what's the relevant code. The code to which I linked in my previous comment is for the 'workspace' or 'project' search and replace features, i.e. the "Searcher".

[Here's the actual code used by the 'find' search and replace features](https://github.com/LightTable/LightTable/blob/c247b3369ece1d0a5f8c98edf8dd93c773187209/src/lt/objs/find.cljs#L117-L123):

```
(behavior ::replace!
          :triggers #{:replace!}
          :reaction (fn [this all?]
                      (when-not (:searching? @this)
                        (object/raise this :search! (->val this)))
                      (js/CodeMirror.commands.replace (editor/->cm-ed (pool/last-active)) (->replacement this) (:reverse? @this) (boolean all?))
                      (object/raise this :next!)))
```

The code above is using [a custom CodeMirror addon (Node module)](https://github.com/LightTable/LightTable/blob/c247b3369ece1d0a5f8c98edf8dd93c773187209/deploy/core/node_modules/codemirror_addons/search.js). [Here's the relevant function](https://github.com/LightTable/LightTable/blob/c247b3369ece1d0a5f8c98edf8dd93c773187209/deploy/core/node_modules/codemirror_addons/search.js#L120-L143):

```
  function replace(cm, text, rev, all) {
    if (all) {
      cm.operation(function() {
        var state = getSearchState(cm);
        for (var cursor = getSearchCursor(cm, state.query); cursor.find(rev);) {
          if (typeof state.query != "string") {
            var match = cm.getRange(cursor.from(), cursor.to()).match(query);
            cursor.replace(text.replace(/\$(\d)/, function(_, i) {return match[i];}));
          } else cursor.replace(text);
        }
      });
    } else {
      var state = getSearchState(cm);
      var cursor = getSearchCursor(cm, state.query, state.posFrom);
      if(cursor.findNext(rev)) {
        cm.setSelection(cursor.from(), cursor.to());
        var match = {};
        if(isRegex(state.query)) {
          match = cm.getRange(cursor.from(), cursor.to()).match(state.query);
        }
        cursor.replace(typeof state.query == "string" ? text :
                       text.replace(/\$(\d)/, function(_, i) {return match[i];}));
      }
    }
  }
```

The example regex replace works in [the 'search' CodeMirror demo](https://codemirror.net/demo/search.html) and there have been no changes to the standard CodeMirror search addon since the version of CodeMirror we're currently using.

**Comment by kenny-evitt** [comment]
Below is a link to a diff between the CodeMirror search addon search module and the LT forked version. The file contains HTML but GitHub doesn't allow files with an HTML file extension to be attached.

[Difference between standard and forked CodeMirror search addon search module.txt](https://github.com/LightTable/LightTable/files/28509/Difference.between.standard.and.forked.CodeMirror.search.addon.search.module.txt)

**Comment by Mouvedia** [comment]
> The example regex replace works in the 'search' CodeMirror demo…

That means that something on our side is amiss.
Anyhow now that we have the relevant code we can test easily if necessary.

**Comment by kenny-evitt** [comment]
@cldwalker [Here's the forked version of the CodeMirror addon module *search.js*.](https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/codemirror_addons/search.js)

[Here's the current CodeMirror version of the same addon module.](https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/codemirror/addon/search/search.js)

[Here's the 'find' code that references our forked module](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/find.cljs#L153-L158):

```
(behavior ::init
          :triggers #{:init}
          :reaction (fn [this]
                      ;; TODO: use addon/search/search.js
                      (load/js "core/node_modules/codemirror_addons/search.js" :sync)
                      (load/js "core/node_modules/codemirror/addon/search/searchcursor.js" :sync)))
```

You added the `TODO` comment – do you remember what exactly you wanted to do? I tried just loading the CodeMirror version, but it didn't work (none of the find features did) and it's pretty obvious why not, given how different the code in each module is. Was the plan to change the LT find code to use the CodeMirror addon? Or fork the newer version?

**Comment by cldwalker** [comment]
@kenny-evitt To give some history on this, I didn't write any of search.js but rather moved it [when cleaning up our codemirror dependency](https://github.com/LightTable/LightTable/commit/f1d33890bda7fbdde7fab6b43b95a0cdd0e05706). As our goal is to get off of forked addons, I created #1778 to track this. This is an excellent chance for a contributor, @Mouvedia or anyone else, to step up and help us use the upstream search.js. This will require understanding what we changed in search.js and working with the CodeMirror team to get those changes merged upstream. If we work with CodeMirror, it only strengthens their community and in turn ours as we can rely on upstream functionality they add. It's worth noting that we're currently on a 4.7 of CodeMirror but the latest is 5.x (being tracked in #1797). So while we do this we have to keep in mind that we'll be doing this while still using an older version of CodeMirror. In the unlikely event that the latest CM has changed the addon API then we would have to block on this until #1797

**Comment by kenny-evitt** [comment]
[Here's the history for *search.js* prior to the move/rename.](https://github.com/LightTable/LightTable/commits/d5953975cc7434e0e55a4b41265e5fab60ee5bf4/deploy/core/node_modules/codemirror/search.js) Unfortunately, there's not a lot of info in the history available. The only changes in the history are [adding the `replace` function](https://github.com/LightTable/LightTable/commit/17eb38c06fdc0497279c8a42bb04b3f3fc723d76) and then making several small fixes:

 - [fix replaces with '(' in them · LightTable/LightTable@e6b16d8](https://github.com/LightTable/LightTable/commit/e6b16d80c82505a5ed79e479ba6ad42c86fbad91)
 - [fix CodeMirror search failing with RegExp syntax · LightTable/LightTable@af73752](https://github.com/LightTable/LightTable/commit/af7375274cce4d5dabc6dc3d206ecc5e6255dca1)
 - [fix regexp replace · LightTable/LightTable@a301f05](https://github.com/LightTable/LightTable/commit/a301f05e6f6489eabbaef092c850c739e2fd7abd)

[I commented about this](https://github.com/LightTable/LightTable/issues/1778#issuecomment-157197928) in #1778.

**Comment by kenny-evitt** [comment]
Please un-assign me.
