### ISSUE TITLE
Search "/" and replace

### ISSUE THREAD

**Issue by devmru** [LightTable/LightTable#1938]
The search can not handle at the beginning and at the end with a "/", and then replaced.

Error:
```
Invalid behavior: :lt.objs.find/replace!
ReferenceError: query is not defined
    at eval (/home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/codemirror_addons/search.js:126:71)
    at runInOp (/home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/codemirror/lib/codemirror.js:2138:18)
    at CodeMirror.operation (/home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/codemirror/lib/codemirror.js:4425:35)
    at Object.replace (/home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/codemirror_addons/search.js:122:10)
    at Function.lt.objs.find.__BEH__replace_BANG_ (file:///home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/lighttable/bootstrap.js:32498:23)
    at c (file:///home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17774:76)
    at a (file:///home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17808:18)
    at a (file:///home/max/LightTable/builds/lighttable-0.8.0-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17819:34)
```
Without the "/" all right

**Comment by kenny-evitt** [comment]
@devmru Would you comment with the exact search and replace text you entered? It's not entirely clear from you original comment.

**Comment by devmru** [comment]
Procedure:
Ctrl+F -> input "find" set value "/var/www/" -> input "replace" set value "/home/max/www/" -> button "all" click -> Error

**Comment by kenny-evitt** [comment]
@devmru thanks

**Comment by rundis** [comment]
Seems to be an issue with the Codemirror search/find plugin.
Can reproduce the problem here: https://codemirror.net/demo/search.html

**Comment by rundis** [comment]
Since it's a regex behind the scenes you'd have to write something like:
Find: /\/var\/www\//
Replace: /\/home\/max\/www\//

**Comment by devmru** [comment]
I did some tests. Problem "/" early search

**Comment by devmru** [comment]
Ctrl+F -> input "find" set value "/var/www/" -> input "replace" set value "/home/max/www/" -> button "all" click -> Error
Ctrl+F -> input "find" set value "var/www/" -> input "replace" set value "/home/max/www/" -> button "all" click -> No error

**Comment by kenny-evitt** [comment]
@devmru @rundis [This seems to be the problematic code](https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/codemirror_addons/search.js#L43-L46):

```
  function isRegex(s) {
    if(s instanceof RegExp) return true;
    return s.match(/^\/(.+)\/([a-z]*)$/);
  }
```

It'd be nice to continue supporting regexes so we need *some* way to distinguish between regular string and regexes. Unless we treat everything like a regex. Maybe we could just treat any `input` as `/input/g`? Or maybe we could tweak the regex-regex in the `isRegex` function to not match `/var/www/`, if that's even possible (or desirable).

As-is, `/var/www/` seems like the perfect input to break something that's trying to support both plain text and regex expressions.

**Comment by danmbox** [comment]
no checkbox to select regex / non-regex search, nice...

**Comment by kenny-evitt** [comment]
@danmbox Pull requests welcome.
