### ISSUE TITLE
LightTable is stalled on startup

### ISSUE THREAD

**Issue by Davidslv** [LightTable/LightTable#1959]
Yesterday as far as I remember I touched the user behaviours to add line numbers, which was showing fine, although when I tried to start Light Table again it stays in that screen and nothing else happens

version: `0.7.2`
OSX version: `10.10.4 (14E46)`

I've tried:

- Force Quit and start Light Table, same result
- Trash it and use a new one, same result
- Trash it, restart, use new one, same result

![screen shot 2015-08-29 at 09 06 22](https://cloud.githubusercontent.com/assets/136777/9561052/824167f4-4e2d-11e5-8744-a55f6830928f.png)

**Comment by kenny-evitt** [comment]
@Davidslv Would you post your *user.behaviors* file?

**Comment by rundis** [comment]
Also @Davidslv You might want to check the logs in ~/Library/Application\ Support/LightTable/logs/ to see if you get any pointers as to what the problem might be

**Comment by Davidslv** [comment]
Hey, thank you for your time answering, so the log says the following:

```clojure
Could not load behaviors for plugin: UserInvalid behavior: :lt.objs.settings/initial-behaviorsError: nth not supported on this type cljs.core/Keyword
    at Error (<anonymous>)
    at c (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3409:15)
    at a (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3419:18)
    at lt.objs.settings.flat_behaviors__GT_map (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:27746:234)
    at lt.objs.settings.parse_file (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:27865:131)
    at eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:7939:51)
    at c (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3982:15)
    at a (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3996:18)
    at cljs.core.LazySeq.cljs$core$IReduce$_reduce$arity$3 (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:5568:31)
```

Unfortunately I don't know where the `user.behaviours` is, but seems pretty much it's the responsible for the crash. What can I do in this situation?

Thank you

**Comment by rundis** [comment]
@Davidslv  ~/Library/Application\ Support/LightTable/User/user.behaviors

**Comment by Davidslv** [comment]
Thanks @rundis, seems I'm not very lucky rollbacking the `user.behaviors` file, I still get the same error.

`Could not load behaviors for plugin: UserInvalid behavior: :lt.objs.settings/initial-behaviorsError: nth not supported on this type cljs.core/Keyword`

**Comment by rundis** [comment]
Feel free to join the gitter room for somewhat more synchronous communication :-)
In the thread you mention, Chris indicated that maybe your user.keymap file has some funkiness in it,

**Comment by Davidslv** [comment]
I've decided to delete the folder ` ~/Library/Application\ Support/LightTable/` and is back to normal.
Thank you for your time :+1:
