### ISSUE TITLE
Problems with plugins with latest source version on Linux

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#2002]
On my Linux box, running Ubuntu 14.04

I'm running the Vim plugin with no issues so I don't *think* there's any issues with plugins in general.

## Markdown

I attempted to installed the plugin from the plugin manager. After closing and re-opening LT, no commands were listed in the command pane.

In my plugin directory, there's a directory named *Markdown-tmp*, and the archive file *Markdown-temp.tar.gz* is also (still) present.

## TernJS

It seemed to have been installed fine but it doesn't work. The errors logged to the console:

```
Invalid behavior: :lt.plugins.tern/start-server
```

```
TypeError: Cannot read property 'call' of undefined
    at Function.__BEH__start_server (/home/kenny/.config/LightTable/plugins/TernJS/ternjs_compiled.js:423:323)
    at c (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17774:76)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17808:18)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17819:34)
    at b (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17823:14)
    at Function.__BEH__try_send (/home/kenny/.config/LightTable/plugins/TernJS/ternjs_compiled.js:510:25)
    at c (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
```

Weirdly, the version shown in the plugin manager is "0.1.9" but the latest version according to the LT plugin metadata (both on GitHub and in my user-app-data directory on my computer) is "0.1.10" – tho maybe that's due to [the plugin's *project.clj* file](https://github.com/mortalapeman/LT-TernJS/blob/master/project.clj#L1) still showing "0.1.9"?

## Plugin QA?

@cldwalker @rundis Does the fact that the Vim plugin seems to be working provide enough evidence that the core plugin functionality is working in the latest version on Linux?

Maybe we should also use a dummy plugin just for QA.

**Comment by cldwalker** [comment]
> After closing and re-opening LT, no commands were listed in the command pane.

You no longer need to do this now that #1990 has landed. You should have gotten an error message in when Markdown failed to install. If not, reproducible steps and a separate issue would be great


> It seemed to have been installed fine but it doesn't work.

TernJS has been buggy so I wouldn't trust it as a good install test. The oudated version number is weird. We only get that information from plugin.{json,edn}. If you can find reproducible steps for it, please file a separate issue.

> Maybe we should also use a dummy plugin just for QA.

I've used the [Whitespace plugin](https://github.com/LightTable/Whitespace/) like that though I do like to install random plugins from time to time as it's good to encounter new cases in QA.

**Comment by kenny-evitt** [comment]
@cldwalker I'll re-test then and open issues on the main repo at first. If appropriate, I'll open issues against each plugin.

**Comment by cldwalker** [comment]
@kenny-evitt Can we close this?

**Comment by Mouvedia** [comment]
@kenny-evitt How did you fix the TernJS bug?

**Comment by kenny-evitt** [comment]
@Mouvedia I think the 0.8.0 release, which included a lot of changes for the migration from node-webkit to { Atom Shell / Electron }, broken the TernJS plugin. See mortalapeman/LT-TernJS#26 for a sorta-recent example that doesn't appear to be fixed in the main plugin repo.
