### ISSUE TITLE
Error selecting "Open recent workspace" from "File" menu or "Workspace" from "View menu on Windows 7

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#2006]
The error:

![image](https://cloud.githubusercontent.com/assets/1461730/10294840/b1c64754-6b8a-11e5-92ef-8c4f501baf36.png)

Text of the error:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Calling a callback of released renderer view
    at ret (C:\@GitHub\LightTable\builds\lighttable-0.8.0-alpha-windows\resources\atom.asar\browser\lib\rpc-server.js:112:21)
    at MenuItem.click (C:\@GitHub\LightTable\builds\lighttable-0.8.0-alpha-windows\resources\atom.asar\browser\api\lib\menu-item.js:44:20)
    at Function.delegate.executeCommand (C:\@GitHub\LightTable\builds\lighttable-0.8.0-alpha-windows\resources\atom.asar\browser\api\lib\menu.js:127:69)

[OK]
```

The "Open recent workspace" item in the context menu of the workspace tree works fine.

**Comment by kenny-evitt** [comment]
I couldn't reproduce this just now. I'll re-open if I re-encounter.
