### ISSUE TITLE
ajax? related exception in log when starting LightTable 0.8-alpha on windows 7

### ISSUE THREAD

**Issue by rundis** [LightTable/LightTable#2026]
Downloaded zip, unpacked and started the exe. (in parallells on a mac)
LT starts but noticed an error message in the console:

```
    SyntaxError: Unexpected end of input
    at Object.parse (native)
    at file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:35374:223
    at file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:23187:14
    at null.<anonymous> (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:23199:16)
    at goog.events.Listener.handleEvent (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:14143:51)
    at Object.goog.events.fireListener (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:14378:12)
    at Object.goog.events.fireListeners_ (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:14368:53)
    at Object.goog.events.dispatchEvent (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:14421:47)
    at goog.events.EventTarget.dispatchEvent (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:14542:22)
    at goog.net.XhrIo.dispatchErrors_ (file:///C:/apps/lighttable-0.8.0-alpha-windows/resources/app/core/node_modules/lighttable/bootstrap.js:16377:62)```

**Comment by rundis** [comment]
not having much luck connecting to clojure projects on windows 7. maybe unrelated.

**Comment by kenny-evitt** [comment]
I had a little trouble connecting a Clojure project on one of my Windows 7 computers, but not on the Windows 7 computer I use most of the time.

**Comment by kenny-evitt** [comment]
I haven't seen this error on the Windows 7 computer I use most of the time.

**Comment by rundis** [comment]
Maybe it's just my parallells/windows setup or somehow some old metadata lying around. I'll try to clean all traces of Light Table and give it another go.

**Comment by rundis** [comment]
I'm getting a very similar exception quite often on my mac. I think I've tracked it down to LT eagerly checking for a new version. And when doing a xhr request to the lighttable github repo it fails for some reason (missing/sketchy connection might be one).

I think some error handling around here would be in order:
https://github.com/LightTable/LightTable/blob/master/src/lt/objs/deploy.cljs#L134

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at lt.objs.deploy.__GT_latest_version (file:///Users/mrundberget/projects/LightTable-Projects/LightTable/builds/lighttable-0.8.0-alpha-mac/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:29037:11)
.....
Failed to load resource: net::ERR_NAME_NOT_RESOLVED: https://api.github.com/repos/LightTable/LightTable/tags

```

**Comment by kenny-evitt** [comment]
That's similar to (or the same as?) the errors I still get accessing some of the GitHub-hosted LT subdomains on my (Windows 7) computer at work – the DNS lookup fails for some reason I couldn't figure out. I don't think anyone else had the same problem so I gave up looking into it.

**Comment by saulshanabrook** [comment]
I have the same problem. Just downloaded Light Table and opened it in El Capitan.

**Comment by saulshanabrook** [comment]
I realized this only happened when I used the `table` CLI command to open the app. If I open it normally, it works fine.
