### ISSUE TITLE
Ubuntu: View workspace from menu gives exception after opening and closing a second window on  

### ISSUE THREAD

**Issue by rundis** [LightTable/LightTable#2066]
* Open a new window
* Close the window again
* select menu item view->workspace

```
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: bootstrap.js:23505:10.
    at ret (/home/parallels/projects/LightTable/builds/lighttable-0.8.0-linux/resources/atom.asar/browser/lib/rpc-server.js:146:21)
    at MenuItem.click (/home/parallels/projects/LightTable/builds/lighttable-0.8.0-linux/resources/atom.asar/browser/api/lib/menu-item.js:58:20)
    at Function.delegate.executeCommand (/home/parallels/projects/LightTable/builds/lighttable-0.8.0-linux/resources/atom.asar/browser/api/lib/menu.js:127:69)
```

**Comment by rundis** [comment]
applies to other menu items like navigator etc too.

**Comment by rundis** [comment]
duplicate of #2017
