### ISSUE TITLE
eval-on-save

### ISSUE THREAD

**Issue by ayzakh** [LightTable/LightTable#2087]
LT version: `0.8.0`
binary version: `0.34.5`

**"ctrl" + "enter"**
---

live-reload works but returns :point_down: 
```
Invalid behavior: :lt.plugins.html/eval-on-save
TypeError: Cannot read property 'call' of null
  at lt.object.has_tag_QMARK_ (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20823:127)
  at lt.objs.clients.placeholder_QMARK_ (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:28856:35)
  at eval (C:%5CProgram%20Files%5Clighttable-0.8.0-windows%5Cresources%5Capp%5Cplugins%5CHTML%5Chtml_compiled.js:27:68)
  at Function.__BEH__eval_on_save (C:%5CProgram%20Files%5Clighttable-0.8.0-windows%5Cresources%5Capp%5Cplugins%5CHTML%5Chtml_compiled.js:31:3)
  at c (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
  at a (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
  at c (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20446:76)
  at a (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20480:18)
  at a (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20491:34)
  at b (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20495:14)
  at Function.<anonymous> (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:30572:48)
  at b (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6188:14)
  at a (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6234:18)
  at a (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21158:29)
  at b (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21162:14)
  at lt.objs.keyboard.trigger (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:23395:128)
  at lt.objs.keyboard.capture (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:23423:139)
  at file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:23495:89
  at Object.Mousetrap.handleKey (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/bootstrap.js:23496:4)
  at HTMLDocument._handleKeyEvent (file:///C:/Program%20Files/lighttable-0.8.0-windows/resources/app/core/node_modules/lighttable/util/keyevents.js:562:21)
```

**Comment by cldwalker** [comment]
Hi. I'm not sure what is meant by a live-reload. Were you doing a ctrl-space eval or saving this file when the error occurred? Could you provide the file that this error occurred on? Without reproducible steps we can't fix this

**Comment by cldwalker** [comment]
Closing as I haven't heard back. Can reopen if given more info as asked

**Comment by endersaka** [comment]
Same problem. Here is the log:
```
Invalid behavior: :lt.plugins.html/eval-on-save
TypeError: Cannot read property 'call' of null
    at lt.object.has_tag_QMARK_ (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20706:127)
    at lt.objs.clients.placeholder_QMARK_ (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28665:35)
    at eval (/private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/plugins/HTML/html_compiled.js:27:68)
    at Function.__BEH__eval_on_save (/private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/plugins/HTML/html_compiled.js:31:3)
    at c (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)
    at a (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20363:18)
    at a (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20374:34)
    at b (file:///private/var/folders/lg/7mj7dbyj28b2_tsgsxx0qx7c0000gn/T/AppTranslocation/22F012CA-5F37-435C-9AB5-6CF0CDC8B3CD/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20378:14)
```

And this is the source code. "bundle.js" is just a bundle generated with Browserify and contains three.js e and the Detector.js example. The bug appears when I press COMMAND-S (platform is Mac OS X 10.12.6) to save the changes to this code.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8>
    <title>My first three.js app</title>
    <style>
      body { margin: 0; }
      canvas { width: 100%; height: 100%; }
    </style>
    <script src="bundle.js"></script>
  </head>
  <body>

    <!-- <script src="node_modules/three/three.js"></script> -->
    <script>
      var THREE = require('three');
      var Detector = require('Detector');

      if (Detector.webgl) {
        // I mattoni fondamentali di una scena in three.js sono:
        // una scena; una camera; e un renderer, che renderizza la
        // scena con la camera.
        var scene = new THREE.Scene();
        var camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
        var renderer = new THREE.WebGLRenderer();

        renderer.setSize(window.innerWidth, window.innerHeight);

        var geometry = new THREE.BoxGeometry(1, 1, 1);
        var material = new THREE.MeshBasicMaterial({color: 0x00ff00});
        var cube = new THREE.Mesh(geometry, material);

        var lineMat = new THREE.LineBasicMaterial({color: 0x0000ff});
        var lineGeom = new THREE.Geometry();
        lineGeom.vertices.push(new THREE.Vector3(-10, 0, 0));
        lineGeom.vertices.push(new THREE.Vector3(0, 10, 0));
        lineGeom.vertices.push(new THREE.Vector3(10, 0, 0));

        var line = new THREE.Line(lineGeom, lineMat);

        scene.add(cube);
        scene.add(line);
        camera.position.z = 20;

        document.body.appendChild(renderer.domElement);

        function animate() {
          window.requestAnimationFrame(animate);

          cube.rotation.x += 0.01;
          cube.rotation.y += 0.01;

          renderer.render(scene, camera);
        }

        animate();
      } else {
        var warning = Detector.getWebGLErrorMessage();
        document.getElementById('container').appendChild(warning);
      }

    </script>
  </body>
</html>
```
