### ISSUE TITLE
Evaluating `@whatever-atom`

### ISSUE THREAD

**Issue by heyarne** [LightTable/LightTable#2092]
When writing clojure and trying to evaluate an expression like `@foo` at the highest level, nothing (visible) happens. To clarify, here is a screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/525780/12074329/dcb48e82-b14c-11e5-9838-3bff8b264c1c.png)

Each line has been evaluated in order using `cmd-enter`. I would have expected `@foo` to have the same effect as `(deref foo)`, am I missing something? I'm using LightTable 0.8 on Mac OSX 10.10.5.

**Comment by heyarne** [comment]
I have just noted that the same goes for evaluating a string, a long, a boolean or a keyword, which suggests to me that this is intended behavior. May I ask why? This comes to me as a surprise as this is quite different from how a classic repl would behave.

**Comment by kenny-evitt** [comment]
@heyarne As-of now, there's no 'reason' why the InstaREPL (or the regular inline eval) fails to print primitive values – it just doesn't. I agree that, being surprising, it should probably be changed to match the unsurprising and standard behavior of other REPLs.

However, none of the core team use the InstaREPL and this isn't particularly useful for inline eval either (as you already know what the value of the expression is). We're also planning on dropping support for the InstaREPL eventually – unless someone steps up to maintain it themselves. If you're willing to work on making the changes tho, one of the three of us on the core team will review a PR with your changes and if they look good we'll gladly merge it.

**Comment by jarcane** [comment]
I've just discovered this as well while doing @swannodette's Light Table CLJS tutorial, which uses the @ deref syntax in the section on atoms: https://github.com/swannodette/lt-cljs-tutorial/blob/master/lt-cljs-tutorial.cljs#L997

**Comment by kenny-evitt** [comment]
@jarcane Pull requests welcome!

**Comment by mikub** [comment]
I am experiencing this issue as well in v.0.8.1. Furthermore I can see the following stack trace in console. The deref works just fine.
`Invalid behavior: :lt.objs.eval/inline-results
TypeError: Cannot read property 'addEventListener' of undefined
    at Function.CodeMirror.on (C:%5CLightTable%5Cresources%5Capp%5Ccore%5Cnode_modules%5Ccodemirror%5Clib%5Ccodemirror.js:7101:16)
    at Function.<anonymous> (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:30923:16)
    at c (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at a (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:20652:136)
    at b (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:20664:14)
    at Function.lt.objs.eval.__BEH__inline_results (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:30936:24)
    at c (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)`

**Comment by kenny-evitt** [comment]
I created LightTable/Clojure#90 to replace this.
