### ISSUE TITLE
Error message does not include the filename

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [LightTable/LightTable#2122]
The unknown file is the file that I was currently working in and trying to run the simulation from inline

![screen shot 2016-01-19 at 8 39 57 am](https://cloud.githubusercontent.com/assets/10747532/12420101/68325758-be88-11e5-9825-fd3945367832.png)

Traceback (most recent call last):
  File "/Applications/LightTable.app/Contents/Resources/app/plugins/Python/py-src/ltmain.py", line 162, in handleEval
    toExec.append(handlePos(code, data[2]["pos"]))
  File "/Applications/LightTable.app/Contents/Resources/app/plugins/Python/py-src/ltmain.py", line 125, in handlePos
    a = ast.parse(string)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 57
    for i in range(0, )
                      ^
SyntaxError: invalid syntax

**Comment by cldwalker** [comment]
Thanks for the report. I'm moving this to the python repo - https://github.com/LightTable/Python/issues/48. I've updated CONTRIBUTING.md to reflect where to report these kind of issues. We are looking for a maintainer for the Python plugin.
