### ISSUE TITLE
LT "updates" to 0.8.1 on every restart

### ISSUE THREAD

**Issue by SnoringFrog** [LightTable/LightTable#2136]
Every time I restart, LT claims it can update to 0.8.1. I say 'dowload and install'; it tells me the install was successful; I close it and restart; the cycle starts over. 

Each time I get these errors in the console:

```
Error: ENOENT: no such file or directory, scandir '/deploy/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at lt.objs.files.full_path_ls (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21994:134)
    at lt.objs.deploy.move_tmp (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28969:215)
    at Extract.<anonymous> (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28988:31)
    at emitNone (events.js:72:20)
    at Extract.emit (events.js:166:7)
    at DirWriter.<anonymous> (/Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/tar/lib/extract.js:66:8)
    at emitNone (events.js:72:20)

Error: ENOENT: no such file or directory, scandir '/Users/430011037/Applications/LightTable.app/Contents/Resources/app/tmp/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at lt.objs.files.full_path_ls (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21994:134)
    at lt.objs.deploy.move_tmp (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28969:70)
    at Extract.<anonymous> (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28988:31)
    at emitNone (events.js:72:20)
    at Extract.emit (events.js:166:7)
    at DirWriter.<anonymous> (/Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/tar/lib/extract.js:66:8)
    at emitNone (events.js:72:20)

Error: ENOENT: no such file or directory, scandir '/deploy/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at lt.objs.files.full_path_ls (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21994:134)
    at lt.objs.deploy.move_tmp (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28969:215)
    at Extract.<anonymous> (file:///Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:28988:31)
    at emitNone (events.js:72:20)
    at Extract.emit (events.js:166:7)
    at DirWriter.<anonymous> (/Users/430011037/Applications/LightTable.app/Contents/Resources/app/core/node_modules/tar/lib/extract.js:66:8)
    at emitNone (events.js:72:20)
```

Running on OSX El Capitan 10.11.1. I open LightTable with this script:

```
source ${HOME}/.bash_profile
LTCLI=true ${HOME}/Applications/LightTable.app/Contents/MacOS/Electron
```

**Comment by kenny-evitt** [comment]
@SnoringFrog What version of LT are (or were) you on before upgrading? You may need to just download the latest version.

**Comment by SnoringFrog** [comment]
I'm on 0.8.0

**Comment by kenny-evitt** [comment]
@SnoringFrog [I also ran into problems upgrading from 0.8.0 to 0.8.1 on a Windows computer.](https://github.com/LightTable/LightTable/issues/2131#issuecomment-175963927)

**Comment by patrickaroo** [comment]
for whatever it's worth, I get the same update prompt on 8.0 every time I start, when I'm on 8.0 already.  OSX El Capitan here.

**Comment by kenny-evitt** [comment]
@patrickaroo Upgrading is broken. See #2138. Tho the latest version is 0.8.1 so maybe something else is broken for you. Feel free to open another issue with sufficient details for someone to reproduce.

**Comment by kenny-evitt** [comment]
I am pretty sure this is caused by the upgrade code being broken – see #2138.

I've got a working fix but it needs to be reviewed (and cleaned-up), and everyone will need to download the next new version manually anyways. You need to also download 0.8.1 to run that version.
