### ISSUE TITLE
plugin template seems not to work

### ISSUE THREAD

**Issue by carocad** [LightTable/LightTable#2139]
Hey guys, I followed the [quick tutorial](https://www.youtube.com/watch?v=j91Li9kL0t8&feature=youtu.be) to get a Lighttable plugin running but when I try to call the 'hello' command, the plugin crashes. Here is the output from the console:

```
Invalid behavior: :lt.objs.sidebar.command/exec-command
TypeError: Cannot read property 'hello' of undefined
    at Function.eval (/home/camilo/.config/LightTable/plugins/clare/src/lt/plugins/clare.cljs[eval2]:28:434)
    at b (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6188:14)
    at a (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6234:18)
    at a (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:18937:29)
    at b (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:18941:14)
    at cljs.core.apply_to (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6097:85)
    at c (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6194:42)
    at a (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at a (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:26631:153)
    at b (file:///home/camilo/software/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:26639:14)
```
As can be seen from the error message, my lighttable version is 0.8.1 with a 0.34.5 binary version in Ubuntu 14.04. I also tried the tutorial shown [here](http://blog.jakubarnold.cz/2014/01/13/light-table-plugin-tutorial.html) but the results that I got are different from those displayed there. Did something change from the versions used to make both tutorials? If so is that documentation outdated or is it a bug in my Lighttable?

PS: In the [gist](https://gist.github.com/darthdeus/8411616) with the code from the written tutorial there is also a user that reports a similar error.

**Comment by cldwalker** [comment]
@carocad  On osx I'm able to generate a new plugin and run the hello command. Could you be more specific about the exact steps that lead to your error? Do you have a github repo that has your failing command? It's hard to debug without reproducible steps

**Comment by carocad** [comment]
@cldwalker No I don't have a github repo of the failing command as I used the code directly given to me by the leiningen template. I was just trying to run my first plugin.
As for the steps they are exactly was being told on the Youtube tutorial. For the sake of clarity here are the steps:

- ```~/.config/Lighttable/plugins/$ lein new lt-plugin clare```
- open Lighttable and add the folder to the workspace
- Evaluate + build connection: Ctrl + Enter
- on the side bar: build file or project
- refresh plugin list
- check that the plugin is installed: show plugin manager
- on the side bar: reload behaviors
- on the side bar: 'clare: hello'

after I execute the hello command the error pops up on the console and no tab nor message appear on lighttable as expected. I know the information that I just gave you is probably not much but that and the console error message are the only thing that I have. Thus my main guess is that the plugin was somehow wrong .... 

Hope it helps

**Comment by carocad** [comment]
@cldwalker after a little introspection I figured out what was the problem. I have my Lighttable configured for executing the whole file on save but somehow that was not working for Clojurescript. When I correctly executed the whole file (Ctrl+ Shift + Enter) then the behaviours were loaded and there was no error on the console. 

Everything as expected. 

PS: I was mislead by the video since in the video, there is no feedback whether or not the file was evaluated (I'm guessing old Lighttable behaviour). So I thought that was normal and didn't bother to check that on mine either. Just for the sake of documentation (in case it happens to someone else), here is a screenshot of how it look when the file was correctly evaluated
![captura de pantalla de 2016-02-04 11 28 48](https://cloud.githubusercontent.com/assets/10408729/12812557/f3f5fd1a-cb32-11e5-8435-f3504d196937.png)

**Comment by cldwalker** [comment]
Thanks for the feedback. Glad you got it working
