### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by mathk** [LightTable/LightTable#2146]
When trying to execute an node 'express' application I have the following issue:

> var app = exports = module.exports = {};
>                   ^
> 
> ReferenceError: exports is not defined
>     at /Users/mathk/git/expresstest/node_modules/express/lib/application.js:37:19
>     at Object.exports.runInContext (vm.js:44:17)
>     at sbRequire (/Applications/LightTable.app/Contents/Resources/app/plugins/Javascript/node/ltnodeclient.js:99:10)
> 

To reproduce:

$ mkdir test
$ node init
$ nam install express --save

Create a file app.js:

```
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

Then add a new connection in LT using the app.js.

Environment:
LT: 0.8.1
OS: OSX 10.11.3
Node: 5.6.0 ( Tested with 4.3.1 and 0.12.7 as well)

**Comment by mathk** [comment]
Post this issue to Javascript repo.
