### ISSUE TITLE
Cannot inline-eval specific clojure expression

### ISSUE THREAD

**Issue by BenWiederhake** [LightTable/LightTable#2162]
I'm not entirely sure where to report this, so feel free to move it as you see fit.

Steps to reproduce:
- Use any editor to write a file with the following five character: `'(())` Since there's lots of escaping going on, here's a sanity check: The parser should parse it as `(quote (()))`, and it should evaluate to "the list that contains exactly one element, and that element is the empty list"
- Open the file using `path/to/LightTable/LightTable /tmp/the/file/from/last/step.clj` so that it knows this is supposed to be Clojure code. I do it this way to avoid a weird GTK+ bug on my machine. I hope this isn't relevant.
- Mark the expression
- Press Ctrl-Return, to trigger inline evaluation of the expression
- Eat a cake while waiting for lein and clojure to boot

Expected behavior:
Stuffed feeling from the cake and the result `(())` being displayed.

Actual behavior:
Stuffed feeling from the cake and ... no result. Instead, the console/error log displays this very lengthy message:
```
Invalid behavior: :lt.objs.eval/inline-results
TypeError: Cannot read property 'addEventListener' of undefined
    at Function.CodeMirror.on (/home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/codemirror/lib/codemirror.js:7101:16)
    at Function.<anonymous> (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:30997:16)
    at c (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at a (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:18548:136)
    at b (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:18560:14)
    at Function.lt.objs.eval.__BEH__inline_results (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:31010:24)
    at c (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///home/eispin/lib/lighttable-0.8.1-linux/resources/app/core/node_modules/lighttable/bootstrap.js:18235:76)
```

Note that trying the same with `(quote (()))` works fine, without any error. Also, just about every sane expression works fine, e.g. `(== 42 1337)`. For contrast, expressions like `'(== 42 1337)` (note the initial apostrophe!) do **not** work.

OS: Debian Testing
LT: 0.8.1
clojure: None from the OS, so it uses whatever ships with LT 0.8.1
leiningen: None from the OS, so it uses whatever ships with LT 0.8.1
LT plugins, according to "plugin manager": Clojure 0.3.2, CSS 0.0.6, JS 0.2.0
Staying Hydrated: This is a pretty long list your "guidelines" want, so I'll go drink a cup of water.
Relevant behaviors: None, I guess. Here's the full, irrelevant list:
```
 [:app :lt.objs.style/set-skin "dark"]
 [:app :lt.objs.plugins/load-js "user_compiled.js"]
 [:editor :lt.objs.editor/no-wrap]
 [:editor :lt.objs.style/set-theme "default"]
 [:editor.clojure :lt.plugins.clojure/print-length 1000]
 [:user.hello :lt.plugins.user/on-close-destroy]
 [:console :lt.objs.console/set-console-limit (* 10 1024)]
```
Relevant keymap bindings: None, I guess. Here's the full, irrelevant list:
```
 [:editor "alt-w" :editor.watch.watch-selection]
 [:editor "alt-shift-w" :editor.watch.unwatch]
 [:editor "ctrl-shift-c" :toggle-comment-selection]
 [:editor "alt-up" :editor.sublime.swapLineUp]
 [:editor "alt-down" :editor.sublime.swapLineDown]
 [:editor "f3" :editor.jump-to-definition-at-cursor]
 [:editor "alt-left" :editor.unjump]
```
Just to confirm: No, I don't recall ever typing `:lt.objs.eval/inline-results` into some file; but I could be wrong. However, `grep -Frn inline-results` tells me that it's probably part of the `default.behaviors`.

This bug does not seem to be already known by the bugtracker.

**Comment by rundis** [comment]
Cheers for the report. I think it's the same issue as https://github.com/LightTable/Clojure/issues/72
so I'm closing this one.

FYI: `:lt.objs.eval/inline-results` is a behavior (think event) that is triggered when the clojure nrepl returns results from an evaluation.
