### ISSUE TITLE
LightTable fails to find plugins behind a proxy

### ISSUE THREAD

**Issue by zsoerenm** [LightTable/LightTable#2174]
LightTable fails to find plugins behind a proxy.

My environment proxy settings are set and work for other applications.
I have also set some npm proxy settings.
`npm config list`
gives me the following output:

```
; cli configs
user-agent = "npm/3.8.3 node/v5.9.1 linux x64"

; userconfig /home/zorn/.npmrc
http-proxy = "http://<proxy_ip>:<proxy_port>/"
https-proxy = "http://<proxy_ip>:<proxy_port>/"
proxy = "http://<proxy_ip>:<proxy_port>/"
registry = "http://registry.npmjs.org/"
strict-ssl = false
```

The error in LightTable is the following:

```
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:51:11)
    at TunnelingAgent.exports.request (http.js:31:10)
    at TunnelingAgent.createSocket (/opt/LightTable/resources/app/core/node_modules/request/tunnel.js:119:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/opt/LightTable/resources/app/core/node_modules/request/tunnel.js:186:41)
    at TunnelingAgent.addRequest (/opt/LightTable/resources/app/core/node_modules/request/tunnel.js:80:8)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (/opt/LightTable/resources/app/core/node_modules/request/main.js:559:30)
    at Request.end (/opt/LightTable/resources/app/core/node_modules/request/main.js:1075:28)
```

**Comment by rundis** [comment]
I think this is related to this known issue: #1984

**Comment by olange** [comment]
@rundis: I encountered the same problem as you I believe, and found a workaround which I described in #1984. May be it'll work for you. Kind regards
