### ISSUE TITLE
LT is not responding, menu was hidden.

### ISSUE THREAD

**Issue by n0h4t** [LightTable/LightTable#2191]
My OS: Elementary Freya 64bit.

I installed LT by following the method on 
`http://askubuntu.com/questions/498505/how-do-i-install-light-table`
At the very first time, everything was OK but when I tried to install some plugin then restarted LT, this happened:

```
Error loading JS file: /home/n0h4t/.config/LightTable/plugins/SCSS/scss_compiled.js : Error: Cannot find module '/home/n0h4t/.config/LightTable/plugins/scss/node_modules/fs-extra'
Error: Cannot find module '/home/n0h4t/.config/LightTable/plugins/scss/node_modules/fs-extra'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at node_require (/home/n0h4t/.config/LightTable/plugins/SCSS/scss_compiled.js:24:72)
    at eval (/home/n0h4t/.config/LightTable/plugins/SCSS/scss_compiled.js:26:51)
    at eval (native)
    at c (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:19310:41)
    at a (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:19318:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:29948:33)
Error loading JS file: /home/n0h4t/.config/LightTable/plugins/Recall/index.js : Error: Cannot find module 'lib/recall'
Error: Cannot find module 'lib/recall'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.requireLocal [as require] (/home/n0h4t/.config/LightTable/plugins/Recall/node_modules/ltrap/index.js:70:7)
    at nodePluginBootstrap (/home/n0h4t/.config/LightTable/plugins/Recall/index.js:23:22)
    at eval (/home/n0h4t/.config/LightTable/plugins/Recall/index.js:25:3)
    at eval (native)
    at c (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:19310:41)
    at a (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:19318:18)
Error loading JS file: /home/n0h4t/.config/LightTable/plugins/PGP/lib/select2.min.js : ReferenceError: jQuery is not defined
ReferenceError: jQuery is not defined
    at eval (/home/n0h4t/.config/LightTable/plugins/PGP/lib/select2.min.js:21:188)
    at eval (native)
    at c (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:19310:41)
    at a (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:19318:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:29948:33)
    at c (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:18235:76)
    at a (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:18259:18)
    at c (file:///opt/lighttable-0.8.1/resources/app/core/node_modules/lighttable/bootstrap.js:18313:169)
Invalid behavior: :lt.objs.menu/create-menu
illegal access
```
The process ID even not appear in top or htop, I can kill it in ksysguard only.
Someone can help me understand why it happens and how to fix this issue? Any help would be appreciated.

**Comment by n0h4t** [comment]
Remove folder ./config/LightTable. Done!
