### ISSUE TITLE
Light Table 0.8.1 doesn't start correctly on osx

### ISSUE THREAD

**Issue by rucka** [LightTable/LightTable#2193]
Hi, 
when I try to start the last version of LT, the main windows open but I'm not able to perform any action and the menu doesn't show any option. When I try to close the application, nothing happens (I have to force quit).
The screenshot shows the logs about opening and the close attempt.
LT runs on Macbook Pro Retina 13-inch Late 2013, OSX El Capitan version 10.11.5 beta.
Any suggestion is appreciate.
Best Regards
Gianluca
<img width="778" alt="screen shot 2016-04-23 at 17 28 33" src="https://cloud.githubusercontent.com/assets/1748351/14762382/f76e0dfa-0978-11e6-92c2-932906121610.png">

**Comment by kenny-evitt** [comment]
@rucka Would you download the 0.8.1 release and run that directly (if that's not what you did)?

If you tried to upgrade an earlier version, it didn't work – see #2138.

**Comment by rucka** [comment]
@kenny-evitt thx for the answer. The first time I tried to upgrade my previous version, but It does not work deleting the older version and retrying to download and open fightable 0.8.1 :(

**Comment by kenny-evitt** [comment]
@rucka Try [deleting the 'user app data'](https://github.com/LightTable/LightTable/issues/1968) before downloading the latest version again.

Let me know if it still doesn't work.

**Comment by rucka** [comment]
@kenny-evitt one step forward... after deleting user app data light table seems to start correctly, but when I try to connect to clojure I receive the error:
```
We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:
final project:  {:description FIXME: write description, :compile-path /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/target/classes, :deploy-repositories [[clojars {:url https://clojars.org/repo/, :password :gpg, :username :gpg}]], :group bs-batch, :license {:name Eclipse Public License, :url http://www.eclipse.org/legal/epl-v10.html}, :resource-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/dev-resources/sample-data /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/dev-resources /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/resources), :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger, #"META-INF/services/.*" [clojure.core/slurp (fn* [p1__949__951__auto__ p2__950__952__auto__] (clojure.core/str p1__949__951__auto__ 
 p2__950__952__auto__)) clojure.core/spit]}, :name bs-batch, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :source-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/src), :eval-in :subprocess, :repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :test-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/test), :aot [bs-batch.pail.split-data-structure bs-batch.pail.data-structure], :target-path /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/target, :prep-tasks [thriftc javac], :java-source-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/src/thrift), :native-path /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/target/native, :offline? false, :root /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch, :pedantic? ranges, :clean-targets [:target-path], :plugins ([lein-thriftc/lein-thriftc 0.1.0]), :url http://example.com/FIXME, :profiles {:dev {:resource-paths (dev-resources/sample-data), :plugins ([lein-thriftc/lein-thriftc 0.1.0]), :prep-tasks [thriftc javac], :jvm-opts nil, :eval-in nil}}, :plugin-repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :global-vars {}, :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/data.xml 0.0.7] [org.clojure/data.csv 0.1.2] [org.clojure/data.json 0.2.5] [org.clojure/tools.cli 0.3.1] [clj-http/clj-http 0.7.7] [clj-time/clj-time 0.6.0] [me.raynes/fs 1.4.4] [org.encog/encog-core 3.1.0] [enclog/enclog 0.6.3] [com.tictactec/ta-lib 0.4.0] [org.apache.hadoop/hadoop-core 1.2.0] [cascalog/cascalog 2.1.1] [clj-pail/clj-pail 0.1.3] [clj-thrift/clj-thrift 0.1.2] [pail-thrift/pail-thrift 0.1.0] [pail-cascalog/pail-cascalog 0.1.0] [org.clojure/tools.nrepl 0.2.10 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.1.3] [lein-light-nrepl-instarepl/lein-light-nrepl-instarepl 0.3.1]), :release-tasks [[vcs assert-committed] [change version leiningen.release/bump-version release] [vcs commit] [vcs tag] [deploy] [change version leiningen.release/bump-version] [vcs commit] [vcs push]], :repl-options {:nrepl-middleware [lighttable.nrepl.handler/lighttable-ops], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name bs-batch 0.1.0-SNAPSHOT, :project (quote {:description FIXME: write description, :compile-path /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/target/classes, :deploy-repositories [[clojars {:url https://clojars.org/repo/, :password :gpg, :username :gpg}]], :group bs-batch, :license {:name Eclipse Public License, :url http://www.eclipse.org/legal/epl-v10.html}, :resource-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/dev-resources/sample-data /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/dev-resources /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/resources), :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger, #"META-INF/services/.*" [clojure.core/slurp (fn* [p1__949__951__auto__ p2__950__952__auto__] (clojure.core/str p1__949__951__auto__ 
 p2__950__952__auto__)) clojure.core/spit]}, :name bs-batch, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :source-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/src), :eval-in :subprocess, :repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :test-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/test), :aot [bs-batch.pail.split-data-structure bs-batch.pail.data-structure], :target-path /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/target, :prep-tasks [thriftc javac], :java-source-paths (/Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/src/thrift), :native-path /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch/target/native, :offline? false, :root /Users/giangi/Projects/-bigdata/cj-brokersquare/bs-batch, :pedantic? ranges, :clean-targets [:target-path], :plugins ([lein-thriftc/lein-thriftc 0.1.0]), :url http://example.com/FIXME, :profiles {:dev {:resource-paths (dev-resources/sample-data), :plugins ([lein-thriftc/lein-thriftc 0.1.0]), :prep-tasks [thriftc javac], :jvm-opts nil, :eval-in nil}}, :plugin-repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :global-vars {}, :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/data.xml 0.0.7] [org.clojure/data.csv 0.1.2] [org.clojure/data.json 0.2.5] [org.clojure/tools.cli 0.3.1] [clj-http/clj-http 0.7.7] [clj-time/clj-time 0.6.0] [me.raynes/fs 1.4.4] [org.encog/encog-core 3.1.0] [enclog/enclog 0.6.3] [com.tictactec/ta-lib 0.4.0] [org.apache.hadoop/hadoop-core 1.2.0] [cascalog/cascalog 2.1.1] [clj-pail/clj-pail 0.1.3] [clj-thrift/clj-thrift 0.1.2] [pail-thrift/pail-thrift 0.1.0] [pail-cascalog/pail-cascalog 0.1.0] [org.clojure/tools.nrepl 0.2.10 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])]), :release-tasks [[vcs assert-committed] [change version leiningen.release/bump-version release] [vcs commit] [vcs tag] [deploy] [change version leiningen.release/bump-version] [vcs commit] [vcs push]], :test-selectors {:default (constantly true)}})})}, :test-selectors {:default (constantly true)}}
Error loading lighttable.nrepl.handler: java.lang.RuntimeException: Unable to resolve var: reader/*alias-map* in this context, compiling:(cljs/analyzer.clj:1499:11)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context, compiling:(/private/var/folders/6b/04d_g1fd5mz1rfqlwzwq49bc0000gn/T/form-init7229337332100453290.clj:1:4699)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6567)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.access$100(Compiler.java:37)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5973)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.eval(Compiler.java:6616)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context
	at clojure.lang.Util.runtimeException(Util.java:219)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:650)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	... 33 more
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at leiningen.core.eval$fn__2428.invoke(eval.clj:236)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.repl$repl.doInvoke(repl.clj:322)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.invoke(light_nrepl.clj:77)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:85)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at leiningen.light_nrepl.main(Unknown Source)
```

Thanks for your support

**Comment by kenny-evitt** [comment]
@rucka That's a familiar issue. See #1052 (or several earlier issues). Hopefully that's covered in [the Clojure plugin "Connection Troubleshooting" section](https://github.com/LightTable/Clojure#connection-troubleshooting). I'd suggest running `lein clean` from your terminal/shell first.
