### ISSUE TITLE
Error loading JS file: juno_compiled.js : Error: Cannot find module 'nw.gui'

### ISSUE THREAD

**Issue by mar348** [LightTable/LightTable#2200]
Dear All,

  It's a big issue for me such as the title. I'm new for using of LightTable. My context is win8.1, 64 bit, Julia-0.4.5, LightTable-0.8.1, and plugins of Julia and Juno for LightTable.

 It prompts me some errors when i launch it:

>  Error loading JS file: C:\Users\kitt\AppData\Roaming\LightTable\plugins\Juno\juno_compiled.js :      Error: Cannot find module 'nw.gui'

    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at eval (C:%5CUsers%5Ckitt%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CJuno%5Cjuno_compiled.js:33:30)
    at eval (native)
    at c (file:///F:/Julia/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21436:41)
    at a (file:///F:/Julia/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21444:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///F:/Julia/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:29874:33)
    at c (file:///F:/Julia/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)

 Any advises are will useful for fix my problem.
 Thanks a lot in advanced.
 Best regards.

**Comment by rundis** [comment]
@mar348 Julia/Juno isn't updated for Light Table 0.8.* which has switched from Node Webkit (nw) to Electron. In addition it appears Juno has switched to Atom but failed to update the docs clearly to indicate that LT support is abandoned. /cc @MikeInnes 

This is not an Light Table issue, but an issue with the plugin(s) you are using.
