### ISSUE TITLE
Repl can't connect after fresh install

### ISSUE THREAD

**Issue by dmbennett** [LightTable/LightTable#2213]
After a fresh install, I cannot run the repl on a .clj file I get this message:

```
We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:
Warning: the Clojure version for this project (1.5.1) does not support reader conditionals. Ultra is falling back to version 0.3.4.
final project:  {:description A local light table project, :compile-path /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/target/classes, :deploy-repositories [[clojars {:url https://clojars.org/repo/, :password :gpg, :username :gpg}]], :group local-client, :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/add-test-hooks! {:color-scheme :solarized_dark, :print-meta false, :map-delimiter , :print-fallback :print, :sort-keys true})), :resource-paths (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/dev-resources /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/resources), :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger, #"META-INF/services/.*" [clojure.core/slurp (fn* [p1__949__951__auto__ p2__950__952__auto__] (clojure.core/str p1__949__951__auto__ 
 p2__950__952__auto__)) clojure.core/spit]}, :name local-client, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :source-paths (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/src), :eval-in :subprocess, :repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :test-paths (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/test), :target-path /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/target, :prep-tasks [javac compile], :native-path /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/target/native, :offline? false, :root /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources, :pedantic? ranges, :clean-targets [:target-path], :plugins ([venantius/ultra 0.3.4]), :plugin-repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :version 0.0.1, :jar-exclusions [#"^\."], :global-vars {}, :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.10 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.1.3] [lein-light-nrepl-instarepl/lein-light-nrepl-instarepl 0.3.1] [mvxcvi/puget 0.8.1] [venantius/ultra 0.3.4] [mvxcvi/whidbey 1.0.0] [im.chit/hara.class 2.1.8] [im.chit/hara.reflect 2.1.8]), :release-tasks [[vcs assert-committed] [change version leiningen.release/bump-version release] [vcs commit] [vcs tag] [deploy] [change version leiningen.release/bump-version] [vcs commit] [vcs push]], :repl-options {:nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values lighttable.nrepl.handler/lighttable-ops], :init (do (do (do (do (clojure.core/require (quote ultra.hardcore)) (clojure.core/require (quote whidbey.repl)) (whidbey.repl/init! nil) (ultra.hardcore/configure! {:color-scheme :solarized_dark, :print-meta false, :map-delimiter , :print-fallback :print, :sort-keys true}))) (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name LightTable-REPL, :project (quote {:description A local light table project, :compile-path /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/target/classes, :deploy-repositories [[clojars {:url https://clojars.org/repo/, :password :gpg, :username :gpg}]], :group local-client, :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/add-test-hooks! {:color-scheme :solarized_dark, :print-meta false, :map-delimiter , :print-fallback :print, :sort-keys true})), :resource-paths (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/dev-resources /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/resources), :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger, #"META-INF/services/.*" [clojure.core/slurp (fn* [p1__949__951__auto__ p2__950__952__auto__] (clojure.core/str p1__949__951__auto__ 
 p2__950__952__auto__)) clojure.core/spit]}, :name local-client, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :source-paths (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/src), :eval-in :subprocess, :repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :test-paths (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/test), :target-path /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/target, :prep-tasks [javac compile], :native-path /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources/target/native, :offline? false, :root /Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/runner/resources, :pedantic? ranges, :clean-targets [:target-path], :plugins ([venantius/ultra 0.3.4]), :plugin-repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :version 0.0.1, :jar-exclusions [#"^\."], :global-vars {}, :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.10 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [mvxcvi/puget 0.8.1] [venantius/ultra 0.3.4] [mvxcvi/whidbey 1.0.0] [im.chit/hara.class 2.1.8] [im.chit/hara.reflect 2.1.8]), :release-tasks [[vcs assert-committed] [change version leiningen.release/bump-version release] [vcs commit] [vcs tag] [deploy] [change version leiningen.release/bump-version] [vcs commit] [vcs push]], :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :init (do (do (clojure.core/require (quote ultra.hardcore)) (clojure.core/require (quote whidbey.repl)) (whidbey.repl/init! nil) (ultra.hardcore/configure! {:color-scheme :solarized_dark, :print-meta false, :map-delimiter , :print-fallback :print, :sort-keys true})))}, :test-selectors {:default (constantly true)}, :monkeypatch-clojure-test false})})) (do (clojure.core/require (quote ultra.hardcore)) (clojure.core/require (quote whidbey.repl)) (whidbey.repl/init! nil) (ultra.hardcore/configure! {:color-scheme :solarized_dark, :print-meta false, :map-delimiter , :print-fallback :print, :sort-keys true}))), :nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}}, :test-selectors {:default (constantly true)}, :monkeypatch-clojure-test false}
Retrieving lein-light-nrepl/lein-light-nrepl/0.1.3/lein-light-nrepl-0.1.3.pom from clojars
Retrieving lein-light-nrepl-instarepl/lein-light-nrepl-instarepl/0.3.1/lein-light-nrepl-instarepl-0.3.1.pom from clojars
Retrieving lein-light-nrepl/lein-light-nrepl/0.3.0/lein-light-nrepl-0.3.0.pom from clojars
Retrieving lein-light-nrepl/lein-light-nrepl/0.1.3/lein-light-nrepl-0.1.3.jar from clojars
Retrieving lein-light-nrepl-instarepl/lein-light-nrepl-instarepl/0.3.1/lein-light-nrepl-instarepl-0.3.1.jar from clojars
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: some? in this context, compiling:(io/aviso/columns.clj:189:11)
	at clojure.lang.Compiler.analyze(Compiler.java:6380)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3573)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2664)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2677)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6009)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2677)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2677)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2677)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6009)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6009)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6009)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.access$100(Compiler.java:37)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:529)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler.eval(Compiler.java:6623)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5417)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at io.aviso.exception$eval6200$loading__4910__auto____6201.invoke(exception.clj:1)
	at io.aviso.exception$eval6200.invoke(exception.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at ultra.colorscheme$eval6194$loading__4910__auto____6195.invoke(colorscheme.clj:1)
	at ultra.colorscheme$eval6194.invoke(colorscheme.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at ultra.hardcore$set_colorscheme_BANG_.invoke(hardcore.clj:51)
	at clojure.lang.Var.invoke(Var.java:423)
	at clojure.lang.AFn.applyToHelper(AFn.java:167)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6468)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6529)
	at clojure.lang.Compiler.eval(Compiler.java:6603)
	at clojure.lang.Compiler.eval(Compiler.java:6582)
	at clojure.core$eval.invoke(core.clj:2852)
	at ultra.hardcore$run_configuration.invoke(hardcore.clj:61)
	at ultra.hardcore$configure_BANG_.invoke(hardcore.clj:76)
	at user$eval6190.invoke(form-init1675527869657231893.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: some? in this context
	at clojure.lang.Util.runtimeException(Util.java:219)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6874)
	at clojure.lang.Compiler.resolve(Compiler.java:6818)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6779)
	at clojure.lang.Compiler.analyze(Compiler.java:6343)
	... 175 more
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at leiningen.core.eval$fn__2428.invoke(eval.clj:236)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.repl$repl.doInvoke(repl.clj:322)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.invoke(light_nrepl.clj:77)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:85)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at leiningen.light_nrepl.main(Unknown Source)

close
```

**Comment by rundis** [comment]
It seems to me your project is using an old version of clojure, but you have plugins or stuff in your profiles.clj that requires a newer clojure version ?

Hard to be sure because you haven't provided anything resembling a [sscce](http://sscce.org). With dependency problems it's a lot of parts to consider; project.clj, project local profiles.clj, global `.lein/profiles.clj`

**Comment by rundis** [comment]
@dmbennett I haven't heard back from you, and I can see little evidence this is a Light Table problem so I'm closing this issue.
