### ISSUE TITLE
If a folder is renamed inside LT, if the rename was unsuccessful, LT displays the renamed folder 

### ISSUE THREAD

**Issue by nmfisher** [LightTable/LightTable#2227]
### Steps to Reproduce

1. Outside LightTable, acquire some handle to a directory that is open in a LightTable workspace (e.g. cd to the directory in Windows cmd.exe)
2. Inside LightTable, right click the folder name and "rename".
3. The folder will appear to have been successfully renamed, though the rename on the filesystem will not occur (and an error is logged to console). The folder will disappear from the workspace when it is next attempted to be opened. Correct behaviour should be to prevent the rename (and perhaps a popup to inform the user that the rename was not successful?).

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |   0.8.1      |
| Operating system                 |    Windows 8.1     |

### Error Messages
Invalid behavior: :lt.objs.sidebar.workspace/rename-folder

Error: EBUSY: resource busy or locked, rename '[original]' -> '[target]'
    at Error (native)
    at Object.fs.renameSync (fs.js:686:18)
    at lt.objs.files.move_BANG_ (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21786:27)
    at Function.lt.objs.sidebar.workspace.__BEH__rename_folder (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:34149:28)
    at c (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)
    at a (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20363:18)
    at a (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20374:34)
    at b (file:///C:/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20378:14)

**Comment by kenny-evitt** [comment]
Thanks for the bug report.
