### ISSUE TITLE
Plugin development: cljs dependency crashes lighttable.nrepl

### ISSUE THREAD

**Issue by tomtau** [LightTable/LightTable#2231]
I'm having a trouble with loading an external cljs dependency (datomic-cljs). I tried various things, including restarting Light Table as suggested here: https://github.com/LightTable/LightTable/issues/2194

My guesses are that it may be caused by cljs incompatibilities or a bug in either LT or Clojure plugin.

Any ideas?

### Steps to Reproduce

 1. create new plugin project: `lein new lt-plugin myplugin`
 2. add `[com.zachallaun/datomic-cljs "0.0.1-alpha-1"]` to project.clj dependencies
 3. open `lt/plugins/logic_test_plugin.cljs`
 4. add some code that uses datomic-cljs, e.g. https://github.com/zachallaun/datomic-cljs#minimum-viable-snippet
 5. save, eval, restart Light Table

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |    0.8.1 (binary version: (0.34.5)     |
| Operating system                 |   Ubuntu 16.04, Win 10, and OSX 10.11.4      |

#### Relevant Plugins

| Plugin | Version |
| ------ | ------- |
| Clojure        | 0.3.3        |

### Error Messages

```
java.lang.NullPointerException

	at lighttable.nrepl.cljs$js_dep.invoke(cljs.clj:195)

	at lighttable.nrepl.cljs$transitive.invoke(cljs.clj:220)

	at lighttable.nrepl.cljs$transitive_all$fn__3974.invoke(cljs.clj:243)

	at clojure.core.protocols$fn__6034.invoke(protocols.clj:143)

	at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)

	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)

	at clojure.core.protocols$fn__6028.invoke(protocols.clj:48)

	at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)

	at clojure.core$reduce.invoke(core.clj:6177)

	at lighttable.nrepl.cljs$transitive_all.invoke(cljs.clj:245)

	at lighttable.nrepl.cljs$compile_all.invoke(cljs.clj:306)

	at lighttable.nrepl.cljs$eval4054$fn__4056.invoke(cljs.clj:351)

	at clojure.lang.MultiFn.invoke(MultiFn.java:227)
	
	at lighttable.nrepl.core$queued$fn__1362.invoke(core.clj:97)

	at clojure.core$comp$fn__4154.invoke(core.clj:2330)

	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__670.invoke(interruptible_eval.clj:159)

	at clojure.lang.AFn.run(AFn.java:24)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)
```

**Comment by carocad** [comment]
@tomtau Lighttable uses internally a very old version of cljs. Therefore a lot of libraries are not compatible as they require newer versions of it. I recommend you to check the releases of your library and see if there is any that matches the version of cljs used in Lighttable.

**Comment by tomtau** [comment]
@carocad I updated the library to match the cljs version: https://github.com/tomtau/datomic-cljs/commit/b5da7b70899f4512e9f6a248ac43cd4863ff4dec
`[tomtau/datomic-cljs "0.0.1-alpha-1"]` (https://clojars.org/tomtau/datomic-cljs )
but still the same issue.
