### ISSUE TITLE
Error in ReactJS based customization

### ISSUE THREAD

**Issue by abhi18av** [LightTable/LightTable#2280]
Hey, so I'm trying to build a simple customization in LightTable using this blogpost on [ReactJS and LightTable](http://blog.brabadu.com/2015/01/reactjs-based-plugin-for-lighttable.html) 

* I double checked that the paths for the user.behaviors  snippets are set correctly *

But I eventually run into the following error log

``` 
at cljs.analyzer$analyze.invoke(analyzer.cljc:2646)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:2654)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2646)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:2653)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2646)
	at lighttable.nrepl.cljs$analyze.invokeStatic(cljs.clj:153)
	at lighttable.nrepl.cljs$analyze.invoke(cljs.clj:152)
	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
	at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:167)
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$mapv.invokeStatic(core.clj:6618)
	at clojure.core$mapv.invoke(core.clj:6618)
	at lighttable.nrepl.cljs$with_analysis$fn__7521$fn__7522.invoke(cljs.clj:161)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1154)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1145)
	at lighttable.nrepl.cljs$with_analysis$fn__7521.invoke(cljs.clj:159)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at lighttable.nrepl.cljs$with_analysis.invokeStatic(cljs.clj:159)
	at lighttable.nrepl.cljs$with_analysis.invoke(cljs.clj:157)
	at lighttable.nrepl.cljs$cljs_dep.invokeStatic(cljs.clj:196)
	at lighttable.nrepl.cljs$cljs_dep.invoke(cljs.clj:193)
	at lighttable.nrepl.cljs$transitive_all$fn__7575.invoke(cljs.clj:249)
	at clojure.lang.PersistentList.reduce(PersistentList.java:141)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at lighttable.nrepl.cljs$transitive_all.invokeStatic(cljs.clj:243)
	at lighttable.nrepl.cljs$transitive_all.invoke(cljs.clj:237)
	at lighttable.nrepl.cljs$compile_all.invokeStatic(cljs.clj:312)
	at lighttable.nrepl.cljs$compile_all.invoke(cljs.clj:311)
	at lighttable.nrepl.cljs$eval7655$fn__7657.invoke(cljs.clj:353)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at lighttable.nrepl.core$queued$fn__1698.invoke(core.clj:96)
	at clojure.core$comp$fn__4727.invoke(core.clj:2459)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__980.invoke(interruptible_eval.clj:159)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And this isn't even all of it so I guess, the crucial hints were missed out. Still, any idea why this is so?

**Comment by Mouvedia** [comment]
> But I eventually run into the following error log

@ what step of the walkthrough?

**Comment by rundis** [comment]
Can you provide an [SSCCE](http://sscce.org/) if you are fairly confident this is something actually wrong with Light Table and not your code. We're keen on trying to keep the issue log relevant for things that needs work. 

If you have questions or need general help, issues is not the way. Please try either the [gitter](https://gitter.im/LightTable/LightTable) room or the [mailing list](https://groups.google.com/forum/#!forum/light-table-discussion) for questions related to developing stuff for Light Table.

btw the stack trace provides no clues to what's wrong. The actual exception might at least be helpful.

**Comment by abhi18av** [comment]
Oh, okay :)

**Comment by abhi18av** [comment]
Well, I was just following the tutorial as it said.

 However, I've contacted the author he says it's probably due to some  breaking changes in React as LT API is pretty stable.

Would you advice using Reagent instead for the little plugin?

**Comment by sbauer322** [comment]
Have you tried to determine the specific version of React the tutorial author used and include that instead? 

I'm not familiar enough with either to recommend one or the other.

**Comment by rundis** [comment]
I would advice you to start without pulling in anything (event hough that means messing with the Dom directly), once you understand how things work properly then you can consider pulling in something like React. 

When it comes to pulling in cljs dependencies please be aware that LT uses a very old version of ClojureScript so you'll probably have a hard time finding versions that are compatible.  I did manage to get an old version of quiescent working though (blog post here: http://rundis.github.io/blog/2015/lt_react.html)

**Comment by rundis** [comment]
closing this down now since I've already notified about where I think discussions and questions should happen :-)
