### ISSUE TITLE
Error on Light Table startup about Example plugin

### ISSUE THREAD

**Issue by focamonca** [LightTable/LightTable#2291]
Just installed LightTable and this is what I get from the console:  

`Error: ENOENT: no such file or directory, open 'C:\Users\Gianmaria\AppData\Roaming\LightTable\plugins\Example\example_compiled.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at c (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21436:91)
    at a (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21444:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:29874:33)
    at c (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)`

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |     0.8.1    |
| Operating system                 |    win 10 64bit     |

#### Relevant Plugins

| Plugin | Version |
| ------ | ------- |
|        |         |  none

#### Relevant Settings in your *user.keymap* and *user.behaviors* Files

*user.keymap*:

```
Paste relevant settings here
```

*user.behaviors*:

```
Paste relevant settings here
```

### Error Messages

```
Error: ENOENT: no such file or directory, open 'C:\Users\Gianmaria\AppData\Roaming\LightTable\plugins\Example\example_compiled.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at c (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21436:91)
    at a (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21444:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:29874:33)
    at c (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///E:/Program%20Files/lighttable-0.8.1-windows/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
```

**Comment by rundis** [comment]
I can understand it's frustrating with errors, but the title for this issue isn't very constructive nor particularly descriptive. Anyways:

First time ever you install Light Table, or maybe you have tried it before on that machine in the past ?

The error basically complains about your user plugin is referencing a plugin called Example that plugin looks to have a .behaviors file that tries to load the compiled js for the plugin.. but there is none. Hence the "ENOENT". AFAIK Light Table doesn't ship with any Example plugin, nor have any reference to any such plugin by default. That's why I'm suspecting you might have had something lying around from the past ?

To be sure:
1) Do you have a folder C:\Users\Glenmaria\AppData\Roaming\LightTable\plugins\Example ? (if so it might be worth deleting it)
2) check your C:\Users\Glenmaria\AppData\Roaming\LightTable\User\plugin.edn file. If that contains an entry for Example in it's dependencies list.. remove it.

might have gotten the path's wrong but hopefully enough info to put you on the right path to resove the error message you get.

**Comment by focamonca** [comment]
AWESOME
THANKS!!!

**Comment by sbauer322** [comment]
I have renamed this issue to be more descriptive.

> AWESOME
> THANKS!!!

Glad to hear Magnus' suggestion has worked out! From the sounds of it, this has been resolved and I am closing the issue.
