### ISSUE TITLE
SyntaxError: Unexpected end of input on Mac 

### ISSUE THREAD

**Issue by jiacai2050** [LightTable/LightTable#2335]
I install the latest version using command below:
```
$ brew cask install lighttable

==> Downloading https://github.com/LightTable/LightTable/releases/download/0.8.1/lighttable-0.8.1-mac.tar.gz
######################################################################## 100.0%
==> Verifying checksum for Cask lighttable
==> Moving App 'LightTable.app' to '/Applications/LightTable.app'.
==> Linking Binary 'light' to '/usr/local/bin/light'.
🍺  lighttable was successfully installed!
```
Then I open lighttable, following error occurs in console:
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:35042:220
    at file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:23033:14
    at null.<anonymous> (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:23045:16)
    at goog.events.Listener.handleEvent (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:14143:51)
    at Object.goog.events.fireListener (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:14378:12)
    at Object.goog.events.fireListeners_ (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:14368:53)
    at Object.goog.events.dispatchEvent (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:14421:47)
    at goog.events.EventTarget.dispatchEvent (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:14542:22)
    at goog.net.XhrIo.dispatchErrors_ (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:16377:62)
```

**Comment by sbauer322** [comment]
Unfortunately, I do not have access to a Mac. @rundis or @cldwalker, can you look into this?

**Comment by pedrorgirardi** [comment]
Hi @jiacai2050,

I did the same on my Mac running macOS Sierra but I couldn't reproduce the error.

**Comment by jiacai2050** [comment]
My mac is also running Sierra `10.12.4 (16E195)`.

I open `Developer Tools` window, and find an error:

```
http://localhost:8315/json Failed to load resource: net::ERR_EMPTY_RESPONSE
```
But I can `curl http://localhost:8315/json` successfully with following response: 
```
$ curl http://localhost:8315/json
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:8315/devtools/page/AEF761E1-34D7-4B58-A9B7-3A95E0D92C81",
   "id": "AEF761E1-34D7-4B58-A9B7-3A95E0D92C81",
   "title": "chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@201276/&amp;can_dock=true&amp;toolbarColor=rgba(223,223,223,1)&amp;textColor=rgba(0,0,0,1)&amp;experiments=true",
   "type": "page",
   "url": "chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@201276/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true",
   "webSocketDebuggerUrl": "ws://localhost:8315/devtools/page/AEF761E1-34D7-4B58-A9B7-3A95E0D92C81"
}, {
   "description": "",
   "id": "BDBD38C3-016D-4F56-91D1-A4BF0AB185D3",
   "title": "Light Table",
   "type": "page",
   "url": "file:///Applications/LightTable.app/Contents/Resources/app/core/LightTable.html?id=1"
} ]
```

Is there anything wrong with my Mac

**Comment by Mouvedia** [comment]
same problem as #2026

**Comment by sbauer322** [comment]
Curious as to what is causing the error to appear again as #2026 had PR https://github.com/LightTable/LightTable/pull/2091 merged in for it.

**Comment by Mouvedia** [comment]
@sbauer322 Probably because it's not shared: if it's generic it should have been.
[The ones](https://github.com/LightTable/LightTable/search?utf8=%E2%9C%93&q=%22js%2FJSON.parse%22) without the `try` are the culprits.

**Comment by sbauer322** [comment]
Ahh, thank you!

**Comment by Mouvedia** [comment]
@sbauer322 good first issue?
