### ISSUE TITLE
Updating Clojure Issues

### ISSUE THREAD

**Issue by bigDaddyS1oth** [LightTable/LightTable#2354]
I was attempting to update the Clojure plugin, and I ran into some errors when I pulled up the console after trying to update it by clicking the "update" button in the Plugin View that wasn't seeming to work. **However** right as I exited Light Table and started it up again to see if anything changed, there was no update option for the Clojure plugin. So while I'm not entirely sure what happened, here are the errors I was seeing in the console:

### Error Messages

```
  Error: Error downloading: https://api.github.com/repos/ZehCnaS34/neon-lt/tarball/0.0.1 status code: 404
    at Error (native)
    at Request.<anonymous> (file:///home/bigdaddytank/lighttable/resources/app/core/node_modules/lighttable/bootstrap.js:28838:11)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/home/bigdaddytank/lighttable/resources/app/core/node_modules/request/main.js:733:12)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

Error: invalid tar file
    at Extract.Parse._startEntry (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/lib/parse.js:144:13)
    at Extract.Parse._process (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/lib/parse.js:125:12)
    at BlockStream.<anonymous> (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/lib/parse.js:46:8)
    at emitOne (events.js:77:13)
    at BlockStream.emit (events.js:169:7)
    at BlockStream._emitChunk (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/node_modules/fstream/lib/reader.js:253:34)
    at Entry.<anonymous> (/home/bigdaddytank/lighttable/resources/app/core/node_modules/tar/lib/parse.js:256:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)

Error: ENOENT: no such file or directory, open '/home/bigdaddytank/.config/LightTable/plugins/Clojure-tmp.tar.gz'
    
```

Not entirely sure if the error `no such file or directory` is a big deal now since everything seems to be fine. And I'm not sure if any of the other errors are an issue for me or for those of you who maintain Light Table, but I listed them just in case.

### Environment

| Info                                     | Details |
| ---------------------------------- | ------- |
| Light Table version              |  0.8.1  |
| Binary Version                     | 0.34.5 |
| Operating system                |   Linux 64-bit  |

**Comment by rundis** [comment]
Looks like the second error is misleading. The actual problem seems to be that there is a theme plugin (neon-lt) in the plugin manager which you tried to install ?, that points to a non existing github repo (hence the 404 in the first error)

**Comment by sbauer322** [comment]
I've opened this issue in the plugin metadata repo to remove the theme: https://github.com/LightTable/plugin-metadata/issues/80

Closing this issue as removing the plugin should resolve the problem.
