### ISSUE TITLE
Segfault on fresh install Arch Linux

### ISSUE THREAD

**Issue by AnonymousDapper** [LightTable/LightTable#2377]
### Steps to Reproduce

 1. Install LT
 2. Open LT

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |     0.8.1-1    |
| Operating system                 |    Arch Linux x64 latest (4.17.6-1)    |

### Error Messages

The only time I get any from LT is when I directly run the binary (`/opt/LightTable/LightTable`).

```
[1]    12372 segmentation fault (core dumped)  ./LightTable
```

**Comment by tmladek** [comment]
Can also confirm on the latest Debian buster, happens also even if I build from source on my machine.

This is the stack trace according to gdb:
```
Thread 1 "LightTable" received signal SIGSEGV, Segmentation fault.
0x00000000010c83eb in ?? ()
(gdb) bt
#0  0x00000000010c83eb in ?? ()
#1  0x00007ffff0de3faf in hb_font_funcs_set_nominal_glyph_func () from /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
#2  0x00007ffff27b292f in ?? () from /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
#3  0x00007ffff64f34a8 in pango_shape_full () from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#4  0x00007ffff64e4f72 in ?? () from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#5  0x00007ffff64e69bb in ?? () from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#6  0x00007ffff64e8f07 in ?? () from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#7  0x00007ffff64ea05a in pango_layout_get_unknown_glyphs_count () from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#8  0x00007ffff69d83f2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x00007ffff69db3b5 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#10 0x00007ffff57e06a5 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff57c15a8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff57c2d45 in g_object_new_with_properties () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff57c37c1 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x000000000196eaea in ?? ()
#15 0x0000000002f45a96 in brightray::BrowserMainParts::ToolkitInitialized() ()
#16 0x000000000229f7a7 in ?? ()
#17 0x00000000022a04eb in ?? ()
#18 0x0000000002298eed in ?? ()
#19 0x00000000010a7881 in ?? ()
#20 0x00000000010a6780 in ?? ()
#21 0x0000000002e6fa97 in main ()
```

**Comment by godlikemouse** [comment]
I'm seeing the exact same think on Arch Linux.  Any ideas on a fix for this?

**Comment by godlikemouse** [comment]
I found a temporary work around, definitely not a fix.  I was able to download [LightTable 0.8.0-alpha](https://github.com/LightTable/LightTable/releases/download/0.8.0-alpha/lighttable-0.8.0-alpha-linux.tar.gz) and run it.  No segfault on start-up and even the font issues with open external file or add folder to workspace are gone.

**Comment by taijiren** [comment]
I was having the same segfault in Arch with 0.8.1, but 0.8.0-alpha worked.
This library fix allowed me to start 0.8.1
https://github.com/ArchI3Chris/LightTable-Square-Fix
Reverting back to libpangoft2-1.0.so.0.4000.5 fixed it, and these instructions simply have you copy the lib (and additional symlink) to the directory containing the LightTable executable... a temporary workaround

**Comment by godlikemouse** [comment]
After doing a full system update:

```
sudo pacman -Syyu
yaourt -Su --aur
```

The latest version of LightTable appears to be working again (version 0.8.1).

**Comment by Selhar** [comment]
Having this exact problem on fedora 29.

**Comment by DWW256** [comment]
I'm getting it here on Ubuntu Studio 18.10 with KDE desktop--not that it appears that that has much to do with it at this point.  Possibly re-file this issue under a more generic name?  "Segfault on startup after fresh install (Linux)"

**Comment by DWW256** [comment]
> 
> 
> After doing a full system update:
> 
> ```
> sudo pacman -Syyu
> yaourt -Su --aur
> ```
> 
> The latest version of LightTable appears to be working again (version 0.8.1).

Any idea what package change might have fixed that?  I know my system is up to date--not as much as Arch though, since it's not rolling--but given that Light Table itself hasn't been updated for over a year, it would be nice to know if another package might have incidentally resolved the issue.

**Comment by tmladek** [comment]
@DWW256 If you look at the stack trace I posted, there seem to be some likely culprits - libharfbuzz, libpangoft2, libpango. Another possibility is be something system-wide font related.

**Comment by godlikemouse** [comment]
@tmladek @DWW256 Agreed, I noticed when doing an update that the LightTable version didn't change but just magically started working again.  That pretty much only leaves some underlying library.  My guess is Pango from my original post.

**Comment by bertalanimre** [comment]
Fedora 29 with latest updates. Still no luck and receiving the same segmentation fault error message. Any idea which packages are exactly needed?

**Comment by godlikemouse** [comment]
I think @tmladek was right, the libraries are: libharfbuzz, libpangoft2, libpango.  Personally, on my distro I found libpango to be the culprit.
