### ISSUE TITLE
Unable to save files via shortcut

### ISSUE THREAD

**Issue by 858master** [LightTable/LightTable#2388]
When I try to save a file using CMD+S the following appears in the console:
`Error: No protocol method IDeref.-deref defined for type null: 
    at Error (native)
    at cljs.core.missing_protocol (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:1460:10)
    at cljs.core._deref (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:2181:38)
    at cljs.core.deref (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:12879:27)
    at lt.objs.document.__GT_stats (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:26524:115)
    at lt.objs.document.save (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:26542:78)
    at Function.lt.objs.editor.file.__BEH__file_save (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:30136:32)
    at c (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///private/var/folders/9t/yhxqm48930bg88sxd48c37jh0000gp/T/AppTranslocation/A3ABBDBA-9223-4F48-A443-628FF8017DE3/d/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)`
How do I avoid that?

**Comment by Mouvedia** [comment]
related: #1293
