### ISSUE TITLE
Can't build from source on Kubuntu 19.10

### ISSUE THREAD

**Issue by Abbath** [LightTable/LightTable#2451]
**Describe the bug**
Can't build from source on Kubuntu 19.10

**Branch**
develop

**To Reproduce**
1. git clone
2. scripts/build.sh
3. build fails

**Expected behavior**
Build does not fail

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux laptop-newer 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 
**Build log**
```
Compiling "deploy/core/node_modules/lighttable/bootstrap.js" from ["src"]...
Compiling "deploy/core/node_modules/lighttable/bootstrap.js" failed.
java.lang.IllegalAccessException: class clojure.lang.Reflector cannot access class jdk.internal.loader.BuiltinClassLoader (in module java.base) because module java.base does not export jdk.internal.loader to unnamed module @143413cd
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
        at java.base/java.lang.reflect.Method.invoke(Method.java:558)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at cljs.closure$get_upstream_deps_STAR_.invoke(closure.clj:1013)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.core$memoize$fn__5049.doInvoke(core.clj:5735)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at cljs.closure$build.invoke(closure.clj:1111)
        at cljs.closure$build.invoke(closure.clj:1105)
        at cljsbuild.compiler$compile_cljs$fn__3141.invoke(compiler.clj:58)
        at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:57)
        at cljsbuild.compiler$run_compiler.invoke(compiler.clj:159)
        at user$eval3267$iter__3270__3274$fn__3275$fn__3287.invoke(form-init2288718024396041760.clj:1)
        at user$eval3267$iter__3270__3274$fn__3275.invoke(form-init2288718024396041760.clj:1)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$dorun.invoke(core.clj:2780)
        at clojure.core$doall.invoke(core.clj:2796)
        at user$eval3267.invoke(form-init2288718024396041760.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.eval(Compiler.java:6609)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.Compiler.loadFile(Compiler.java:7020)
        at clojure.main$load_script.invoke(main.clj:294)
        at clojure.main$init_opt.invoke(main.clj:299)
        at clojure.main$initialize.invoke(main.clj:327)
        at clojure.main$null_opt.invoke(main.clj:362)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
Subprocess failed
```

**Comment by StarrKiss** [comment]
Same exact error here on Manjaro Linux on a t490s

**Comment by prertik** [comment]
Please build from `master` branch.

**Comment by prertik** [comment]
BTW, what's your `jdk` version?
