### ISSUE TITLE
"We couldn't connect"

### ISSUE THREAD

**Issue by KarateCoder57** [LightTable/LightTable#2487]
**Describe the bug**
Cannot figure out how to connect to a Clojure file to run the REPL
**Version**
LightTable 0.8.1
**To Reproduce**
Steps to reproduce the behavior:.

(Using Windows 10 Home)
1. Install AdoptOpenJDK 11 HotSpot
2. Install LightTable
3. Create or open clojure file
4. Try to run REPL (Ctrl. + Enter)

**Expected behavior**
REPL Opens.

**Actual Behavior**
"Looks like there was a issue trying to connect to the project. Here's what we got:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at dynapath.defaults__init.load(Unknown Source)
	at dynapath.defaults__init.&lt;clinit&gt;(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at dynapath.util$loading__5340__auto____274.invoke(util.clj:1)
	at dynapath.util__init.load(Unknown Source)
	at dynapath.util__init.&lt;clinit&gt;(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at cemerick.pomegranate$loading__5340__auto____29.invoke(pomegranate.clj:1)
	at cemerick.pomegranate__init.load(Unknown Source)
	at cemerick.pomegranate__init.&lt;clinit&gt;(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at leiningen.core.project$loading__5340__auto____27.invoke(project.clj:1)
	at leiningen.core.project__init.load(Unknown Source)
	at leiningen.core.project__init.&lt;clinit&gt;(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at leiningen.light_nrepl$loading__5340__auto____25.invoke(light_nrepl.clj:1)
	at leiningen.light_nrepl__init.load(Unknown Source)
	at leiningen.light_nrepl__init.&lt;clinit&gt;(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at leiningen.light_nrepl.&lt;clinit&gt;(Unknown Source)
Caused by: java.lang.ClassNotFoundException: sun.misc.Launcher$ExtClassLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at dynapath.defaults$fn__343.&lt;clinit&gt;(defaults.clj:12)
	... 106 more

**Comment by KarateCoder57** [comment]
Just tried with AdoptOpenJDK 8 HotSpot and got this, seems less cryptic:

final project:  {:description FIXME: write description, :compile-path C:\Users\blade\Documents\clojure-spellchecker\target\base+system+user+dev+80fd729b\classes, :deploy-repositories [[clojars {:url https://clojars.org/repo/, :password :gpg, :username :gpg}]], :group clojure-spellchecker, :license {:name EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0, :url https://www.eclipse.org/legal/epl-2.0/}, :resource-paths (C:\Users\blade\Documents\clojure-spellchecker\dev-resources C:\Users\blade\Documents\clojure-spellchecker\resources), :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger, #"META-INF/services/.*" [clojure.core/slurp (fn* [p1__953__955__auto__ p2__954__956__auto__] (clojure.core/str p1__953__955__auto__ 
 p2__954__956__auto__)) clojure.core/spit]}, :name clojure-spellchecker, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :source-paths (C:\Users\blade\Documents\clojure-spellchecker\src), :eval-in :subprocess, :repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :test-paths (C:\Users\blade\Documents\clojure-spellchecker\test), :target-path C:\Users\blade\Documents\clojure-spellchecker\target\base+system+user+dev+80fd729b, :prep-tasks [javac compile], :native-path C:\Users\blade\Documents\clojure-spellchecker\target\base+system+user+dev+80fd729b\native, :offline? false, :root C:\Users\blade\Documents\clojure-spellchecker, :pedantic? ranges, :clean-targets [:target-path], :plugins [], :url http://example.com/FIXME, :profiles {:uberjar {:aot [:all], :jvm-opts nil, :eval-in nil}}, :plugin-repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :main clojure-spellchecker.core, :global-vars {}, :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :dependencies ([org.clojure/clojure 1.10.1] [org.clojure/tools.nrepl 0.2.10 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.3.3] [lein-light-nrepl-instarepl/lein-light-nrepl-instarepl 0.3.1]), :release-tasks [[vcs assert-committed] [change version leiningen.release/bump-version release] [vcs commit] [vcs tag] [deploy] [change version leiningen.release/bump-version] [vcs commit] [vcs push]], :repl-options {:nrepl-middleware [lighttable.nrepl.handler/lighttable-ops], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name clojure-spellchecker 0.1.0-SNAPSHOT, :project (quote {:description FIXME: write description, :compile-path C:\Users\blade\Documents\clojure-spellchecker\target\base+system+user+dev\classes, :deploy-repositories [[clojars {:url https://clojars.org/repo/, :password :gpg, :username :gpg}]], :group clojure-spellchecker, :license {:name EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0, :url https://www.eclipse.org/legal/epl-2.0/}, :resource-paths (C:\Users\blade\Documents\clojure-spellchecker\dev-resources C:\Users\blade\Documents\clojure-spellchecker\resources), :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger, #"META-INF/services/.*" [clojure.core/slurp (fn* [p1__953__955__auto__ p2__954__956__auto__] (clojure.core/str p1__953__955__auto__ 
 p2__954__956__auto__)) clojure.core/spit]}, :name clojure-spellchecker, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :source-paths (C:\Users\blade\Documents\clojure-spellchecker\src), :eval-in :subprocess, :repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :test-paths (C:\Users\blade\Documents\clojure-spellchecker\test), :target-path C:\Users\blade\Documents\clojure-spellchecker\target\base+system+user+dev, :prep-tasks [javac compile], :native-path C:\Users\blade\Documents\clojure-spellchecker\target\base+system+user+dev\native, :offline? false, :root C:\Users\blade\Documents\clojure-spellchecker, :pedantic? ranges, :clean-targets [:target-path], :plugins [], :url http://example.com/FIXME, :profiles {:uberjar {:aot [:all], :jvm-opts nil, :eval-in nil}}, :plugin-repositories [[central {:url https://repo1.maven.org/maven2/, :snapshots false}] [clojars {:url https://clojars.org/repo/}]], :version 0.1.0-SNAPSHOT, :jar-exclusions [#"^\."], :main clojure-spellchecker.core, :global-vars {}, :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :dependencies ([org.clojure/clojure 1.10.1] [org.clojure/tools.nrepl 0.2.10 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])]), :release-tasks [[vcs assert-committed] [change version leiningen.release/bump-version release] [vcs commit] [vcs tag] [deploy] [change version leiningen.release/bump-version] [vcs commit] [vcs push]], :test-selectors {:default (constantly true)}})})}, :test-selectors {:default (constantly true)}}
Retrieving org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.pom from central
Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.pom from clojars
Retrieving lein-light-nrepl/lein-light-nrepl/0.3.3/lein-light-nrepl-0.3.3.pom from clojars
Retrieving org/clojure/clojure/1.7.0/clojure-1.7.0.pom from central
Retrieving org/clojure/clojure/1.2.0/clojure-1.2.0.pom from central
Retrieving commons-io/commons-io/2.4/commons-io-2.4.pom from central
Retrieving org/apache/commons/commons-parent/25/commons-parent-25.pom from central
Retrieving org/clojure/tools.reader/0.9.2/tools.reader-0.9.2.pom from central
Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.pom from central
Retrieving clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.pom from clojars
Retrieving org/clojure/clojurescript/0.0-3308/clojurescript-0.0-3308.pom from central
Retrieving org/clojure/clojure/1.7.0-RC1/clojure-1.7.0-RC1.pom from central
Retrieving com/google/javascript/closure-compiler/v20150505/closure-compiler-v20150505.pom from central
Retrieving com/google/javascript/closure-compiler-parent/v20150505/closure-compiler-parent-v20150505.pom from central
Retrieving com/google/javascript/closure-compiler-externs/v20150505/closure-compiler-externs-v20150505.pom from central
Retrieving args4j/args4j/2.0.26/args4j-2.0.26.pom from central
Retrieving args4j/args4j-site/2.0.26/args4j-site-2.0.26.pom from central
Retrieving org/kohsuke/pom/6/pom-6.pom from central
Retrieving com/google/guava/guava/18.0/guava-18.0.pom from central
Retrieving com/google/guava/guava-parent/18.0/guava-parent-18.0.pom from central
Retrieving com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.pom from central
Retrieving com/google/google/1/google-1.pom from central
Retrieving com/google/code/gson/gson/2.2.4/gson-2.2.4.pom from central
Retrieving com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom from central
Retrieving org/clojure/google-closure-library/0.0-20150505-021ed5b3/google-closure-library-0.0-20150505-021ed5b3.pom from central
Retrieving org/clojure/google-closure-library-third-party/0.0-20150505-021ed5b3/google-closure-library-third-party-0.0-20150505-021ed5b3.pom from central
Retrieving org/clojure/data.json/0.2.6/data.json-0.2.6.pom from central
Retrieving org/mozilla/rhino/1.7R5/rhino-1.7R5.pom from central
Retrieving clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.pom from clojars
Retrieving lein-light-nrepl-instarepl/lein-light-nrepl-instarepl/0.3.1/lein-light-nrepl-instarepl-0.3.1.pom from clojars
Retrieving lein-light-nrepl/lein-light-nrepl/0.3.0/lein-light-nrepl-0.3.0.pom from clojars
Retrieving commons-io/commons-io/2.4/commons-io-2.4.jar from central
Retrieving org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.jar from central
Retrieving org/clojure/tools.reader/0.9.2/tools.reader-0.9.2.jar from central
Retrieving org/clojure/clojurescript/0.0-3308/clojurescript-0.0-3308.jar from central
Retrieving com/google/javascript/closure-compiler-externs/v20150505/closure-compiler-externs-v20150505.jar from central
Retrieving com/google/javascript/closure-compiler/v20150505/closure-compiler-v20150505.jar from central
Retrieving com/google/guava/guava/18.0/guava-18.0.jar from central
Retrieving args4j/args4j/2.0.26/args4j-2.0.26.jar from central
Retrieving com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar from central
Retrieving com/google/code/gson/gson/2.2.4/gson-2.2.4.jar from central
Retrieving com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar from central
Retrieving org/clojure/google-closure-library/0.0-20150505-021ed5b3/google-closure-library-0.0-20150505-021ed5b3.jar from central
Retrieving org/clojure/google-closure-library-third-party/0.0-20150505-021ed5b3/google-closure-library-third-party-0.0-20150505-021ed5b3.jar from central
Retrieving org/clojure/data.json/0.2.6/data.json-0.2.6.jar from central
Retrieving org/mozilla/rhino/1.7R5/rhino-1.7R5.jar from central
Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar from clojars
Retrieving clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.jar from clojars
Retrieving lein-light-nrepl/lein-light-nrepl/0.3.3/lein-light-nrepl-0.3.3.jar from clojars
Retrieving lein-light-nrepl-instarepl/lein-light-nrepl-instarepl/0.3.1/lein-light-nrepl-instarepl-0.3.1.jar from clojars
Error loading lighttable.nrepl.handler: Syntax error macroexpanding clojure.core/ns at (cljs/source_map/base64_vlq.clj:1:1).
Syntax error compiling var at (C:\Users\blade\AppData\Local\Temp\form-init816432178064976695.clj:1:5085).
Unable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context

Full report at:
**C:\Users\blade\AppData\Local\Temp\clojure-4926503175162933685.edn**
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at leiningen.core.eval$fn__2432.invoke(eval.clj:236)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.repl$repl.doInvoke(repl.clj:322)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.invoke(light_nrepl.clj:77)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:85)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at leiningen.light_nrepl.main(Unknown Source)

**Comment by KarateCoder57** [comment]
Here's the contents of the full report mentioned above in C:\Users\blade\AppData\Local\Temp\clojure-4926503175162933685.edn

{:clojure.main/message
 "Syntax error compiling var at (C:\\Users\\blade\\AppData\\Local\\Temp\\form-init816432178064976695.clj:1:5085).\r\nUnable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context\r\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 5085,
  :clojure.error/source "form-init816432178064976695.clj",
  :clojure.error/symbol var,
  :clojure.error/path
  "C:\\Users\\blade\\AppData\\Local\\Temp\\form-init816432178064976695.clj",
  :clojure.error/class java.lang.RuntimeException,
  :clojure.error/cause
  "Unable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error compiling var at (C:\\Users\\blade\\AppData\\Local\\Temp\\form-init816432178064976695.clj:1:5085).",
    :data
    {:clojure.error/phase :compile-syntax-check,
     :clojure.error/line 1,
     :clojure.error/column 5085,
     :clojure.error/source
     "C:\\Users\\blade\\AppData\\Local\\Temp\\form-init816432178064976695.clj",
     :clojure.error/symbol var},
    :at [clojure.lang.Compiler analyzeSeq "Compiler.java" 7115]}
   {:type java.lang.RuntimeException,
    :message
    "Unable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context",
    :at [clojure.lang.Util runtimeException "Util.java" 221]}],
  :trace
  [[clojure.lang.Util runtimeException "Util.java" 221]
   [clojure.lang.Compiler$TheVarExpr$Parser parse "Compiler.java" 720]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$InvokeExpr parse "Compiler.java" 3888]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7109]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$InvokeExpr parse "Compiler.java" 3888]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7109]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler access$300 "Compiler.java" 38]
   [clojure.lang.Compiler$LetExpr$Parser parse "Compiler.java" 6384]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$BodyExpr$Parser parse "Compiler.java" 6120]
   [clojure.lang.Compiler$FnMethod parse "Compiler.java" 5467]
   [clojure.lang.Compiler$FnExpr parse "Compiler.java" 4029]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7105]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler eval "Compiler.java" 7174]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Unable to resolve var: lighttable.nrepl.handler/lighttable-ops in this context",
  :phase :compile-syntax-check}

**Comment by KarateCoder57** [comment]
Alright, I was able to make it work with a new .clj file. Still have not been able to make it work with my project started with leiningen. Guessing it has to do with that other issue talking about uberjar.

**Comment by KarateCoder57** [comment]
Alright, I was finally able to make it work with a project auto generated from Leiningen after finding this: https://github.com/LightTable/Clojure#connection-troubleshooting and changing the project.clj to require Clojure 1.7.0 instead of 1.10.0.

Looks like this could be three separate issues: 

1. Cannot connect with Java 11.
2. Cannot connect to a default lein generated project (Because LightTable is apparently requiring Clojure 1.7.0)
3. It would be really helpful to have a link to the troubleshooting docs from the dialog that informs you that you cannot connect.
