### ISSUE TITLE
Mongoose breaks requiring in NodeJS (0.4.1)

### ISSUE THREAD

**Issue by tp** [LightTable/LightTable#491]
Reproduce with a simple test file:

```
var mg = require('mongoose');
```

Which results in this:

```
mongooseRequirer.js[stderr]:
vm.runInContext(fs.readFileSync(path), sb, path);
         ^
SyntaxError: Unexpected token :
    at sbRequire (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:96:10)
    at req (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:78:12)
    at /Users/timm/Projects/x/node_modules/mongoose/lib/index.js:428:30
    at sbRequire (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:96:10)
    at req (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:78:12)
    at /Users/timm/Projects/x/node_modules/mongoose/index.js:7:18
    at sbRequire (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:96:10)
    at req (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:78:12)
    at /Users/timm/Projects/x/mongooseRequirer.js:1:10
    at sbRequire (/Users/timm/.lighttable/plugins/nodejs/ltnodeclient.js:96:10)
```

**Comment by rbecheras** [comment]
I have the same issue with LT v0.8.1.
I wrote a PR in LT/Javascript project: https://github.com/LightTable/Javascript/pull/22
